### ISSUE TITLE
Videos don't start on HBO GO when extension is enabled

### ISSUE THREAD

**Issue by mariusi7** [igrigorik/videospeed#199] opened 2017-04-09 07:45 UTC
I'm trying to see some videos (probably Silverlight?), they work in Incognito when VSC is disabled, but not in normal mode.Trying to see if I can speed up the video on this site but somehow, the extension makes them not play at all.
Example:
https://www.hbogo.ro/content/togetherness-1-family-day-834924115

**Comment by igrigorik** [comment] 2017-04-09 15:46
> I'm trying to see some videos (probably Silverlight?), they work in Incognito when VSC is disabled, but not in normal mode.

Sounds like the player and extension are not playing nicely together. Unfortunately I can't access the link to test.. are there any public (no login required) videos on that site that we can test?

**Comment by mariusi7** [comment] 2017-04-09 16:02
There's a section with free vids called "Fara abonament" in the menu, direct link: https://www.hbogo.ro/group/free
The first video was one of them. Try to start from there with any video.
If all fail, maybe you have HBO Go in your country and they have a similar free section and same player ?

**Comment by igrigorik** [comment] 2017-04-09 16:54
- hbogo.ro gives me an "out of service" error. Guessing, due to geo restrictions.
- http://www.hbo.com/watch-free-episodes - loads + plays fine. Can you confirm?
- http://play.hbogo.com/episode/urn:hbo:episode:GVU47sw4_D1FvjSoJAeYA - clicking "preview" asks me to install Flash -- fail.

Hmm..

**Comment by mariusi7** [comment] 2017-04-09 17:11
Yes, I confirm the preview from hbo.com loads and can be speed up. The hbogo.com link gives me Access Denied or geo-restricted for direct hbogo.com.
Indeed HBO GO from outside the region give an "out of service", I just tried for hbogo.bg.
So it seems there's no way to you to test this unfortunately :(

**Comment by igrigorik** [comment] 2017-04-09 17:18
How comfortable are you with Chrome DevTools? Can you inspect the page on your end and check if its a video element or flash? Any exceptions being triggered in the console?

**Comment by mariusi7** [comment] 2017-04-09 17:37
Do these help you? There are a bunch of errors when it's not playing, some of which repeat when it is (with the extension off). The video is not present in Inspect when it fails to play.
![inspect_when_not_working](https://cloud.githubusercontent.com/assets/27129454/24839495/32efc724-1d64-11e7-9151-127ec35f5e62.png)
![inspect_when_working](https://cloud.githubusercontent.com/assets/27129454/24839493/32ea49a2-1d64-11e7-8f7b-3a15364035da.png)
![errors-when_working](https://cloud.githubusercontent.com/assets/27129454/24839496/32f06ab2-1d64-11e7-9dc4-c59069c5f0a6.png)
![errors-when_not_working](https://cloud.githubusercontent.com/assets/27129454/24839494/32ef8cc8-1d64-11e7-9ad8-2e6a1c0eee51.png)

**Comment by mariusi7** [comment] 2017-04-09 17:39
1st and 4th screen are when it's not playing, 2nd and 3rd as comparison from an Incognito tab where it's playing.

**Comment by igrigorik** [comment] 2017-04-11 02:07
Hmm, it does help.. A few things we can see:

- The site does use HTML5 video, which is a good sign.
 - It looks like the player is https://demo.castlabs.com - that works though.
- In console logs, by the red funnel image there is a drop down that says "top". Can you please switch to the video controller and capture the logs from that? If there are any..

**Comment by mariusi7** [comment] 2017-04-11 13:04
Hi.
It's not always the same but this shows up most times:
![p2](https://cloud.githubusercontent.com/assets/27129454/24910319/08594ad6-1ed0-11e7-9d3b-13b62be8bb43.png)
The "observe" error appears in Incognito too (in the page before I press play), so I guess it can be ignored.
I also captured the Logs tab:
![logs](https://cloud.githubusercontent.com/assets/27129454/24910423/61605afc-1ed0-11e7-91ea-7fd36d40cd72.png)

**Comment by mariusi7** [comment] 2017-04-16 09:24
Hi. Did some more tests with enabling all other extensions in Incognito except VSC and video plays. 
Tried to debug myself a bit the errors but couldn't find what makes the player fail.

The other idea I had is to find a player you can test on.
And I think/hope I found one that plays in any region?
So please try to debug on any free video from HBO GO Poland: http://www.hbogo.pl/group/free
Worked for me outside PL (unlike other HBO GO websites) and the same behavior is present. 
Thanks!

**Comment by igrigorik** [comment] 2017-04-23 16:54
Nope, no luck. I tried to VPN through Poland/Romania, but guessing they have those IP's blacklisted because I just get the same "out of service" -- sigh.

Can you try switching to the "video speed controller" section (see https://github.com/igrigorik/videospeed/issues/199#issuecomment-293129010, last bullet point) and see what errors (if any) you see there?

**Comment by mariusi7** [comment] 2017-04-23 17:15
That's unfortunate :(.
So the last screen is not correct? It's supposed to be switched to "vsc" section already. Let me know what I'm not doing right.
New test/screen: 
![2017-04-23 20_14_04-program manager](https://cloud.githubusercontent.com/assets/27129454/25315664/84e89d28-2861-11e7-8993-b9feb4359369.png)

**Comment by igrigorik** [comment] 2017-04-23 17:30
Oh, my bad, that is the right screen. I don't see any issues there though that would explain why the videos don't work.. Unfortunately not sure what else we can do here to fix this, I'd need a way to test what's going on. Interestingly enough, everything seems to be working on the US version, so perhaps the player in Romania is lagging behind? My recommendations here: 

- you can blacklist HBO Go in your extension settings to get the videos to play
- ping HBO support and route them to this bug?

**Comment by igrigorik** [comment] 2017-06-25 19:42
Can't reproduce, closing.. Please feel free to reopen if this persists + there is some new insights that can help us track it down.

**Comment by mariusi7** [comment] 2017-08-07 09:39
Hi again.
I didn't give up and debugged again (since it's the same in Mozilla).
Seems the site (in my case hbogo.ro) needs the same treatment as "www.amazon.com". Probably because before the movie starts, there's a "copyright warning" overlay.
Worked when in debug I did this:
http://imgur.com/a/pJYBY
@igrigorik  could you modify the code to do that? As a switch-case branch or something smarter that detects where to insert.

**Comment by mariusi7** [comment] 2017-08-07 09:46
@igrigorik  Could you reopen please? Seems I am unable ("you cannot re-open your own issues if a repo collaborator closed them") or don't know how.

**Comment by igrigorik** [comment] 2017-08-07 13:53
Nice, thanks for tracking this down! Reopening.

Adding hbo to the switch is simple enough, but are you sure same problem is present on all HBO sites? In my earlier testing I couldn't reproduce it on the .com site (in preview mode, I don't have an HBO subscription). Detecting the overlay is tricky.. so I think we should stick with origin based inject.

**Comment by mariusi7** [comment] 2017-08-07 15:20
I can only confirm that the same HBO GO interface is used for all EU sites I tried. They all have the hostname "www.hbogo.*" (list here http://www.hbogo.eu). Can't access hbogo,com, HBO NOW (US, UK, Canada). 
If we can't find a friend or user to test those, I'm fine with a hardcoded setting only for my .ro domain. Or maybe a new (advanced) configuration box in GUI where one can add domains that have an overlay?

**Comment by igrigorik** [comment] 2017-08-07 15:26
If its behaving like this on all EU sites, chances are.. it's not an isolated problem. Let's take the regex route, as you suggested earlier. Up for making a PR for this? :)

**Comment by mariusi7** [comment] 2017-08-07 16:14
Sure. Just let me know what to do (new to github)

**Comment by igrigorik** [comment] 2017-08-07 16:33
Ah, take a look at the GitHub docs: https://help.github.com/articles/creating-a-pull-request/ -- hope that helps! :)

**Closed** 2017-08-08 15:07 UTC
Labels: blocked:feedback

**Comment by Dannniello** [comment] 2017-09-09 18:12
Are these changes already present in Video Speed Controller 0.4.8.1?
Because I have similar issue, but with https://www.hbogo.pl/ website...

Firefox 57.0a1 (2017-09-08) (64 bits) on Fedora 25 + Video Speed Controller 0.4.8.1

When Video Speed Controller is enabled - video on website https://www.hbogo.pl/ will not start.
Workaround:
1. Go to about:addons
2. Disable Video Speed Controller
3. Play video on https://www.hbogo.pl/
4. Enable Video Speed Controller

This workaround is working well - Video Speed Controller will work on already started hbogo.pl video, but enable/disable extension via about:addons is very uncomfortable...

Video Speed Controller has menu icon with "Settings", "Send feedback" and "About".
Could you add button "On/Off" to this menu?

**Comment by igrigorik** [comment] 2017-09-09 18:25
Latest version is 0.4.9... and, we publish Chrome extension only. Looks like someone is mirroring it for Firefox? :)

**Comment by Dannniello** [comment] 2017-09-09 18:34
Ugh... Sorry, my mistake... Yes, I'm using fork of your extension:
https://addons.mozilla.org/en-GB/firefox/addon/videospeed/
https://github.com/codebicycle/videospeed/

**Comment by mariusi7** [comment] 2017-09-09 18:37
He promised to do a new Firefox version once this gets one. I reminded him in https://github.com/codebicycle/videospeed/pull/7

**Comment by Dannniello** [comment] 2017-09-09 18:41
Thank you!

**Comment by mariusi7** [comment] 2017-09-24 07:19
They changed the hbogo site a few days ago (at least my country version, PL looks to be the same as before) and today I noticed that "www" is stripped from the URL and can't be manually put back. Unfortunately the change I did for version 3.4.9 used a match for "www,hbogo.*", so the fix does not work anymore (video will again not play). 
Created https://github.com/igrigorik/videospeed/pull/267
