### ISSUE TITLE
vimeo: control enters full screen

### ISSUE THREAD

**Issue by bethrobson** [igrigorik/videospeed#425] opened 2019-01-18 17:19 UTC
When I use the control to increase or decrease the video speed in vimeo, it causes the video to enter full screen. So I click +, it goes into full screen, so I have to press escape to get back into regular mode, I click + again and again it goes to full screen, etc.

**Comment by azuzunaga** [comment] 2019-01-23 18:06
@bethrobson, I have the same issue. I've gotten around it by using `shift + <keyboard shortcut>` (I've been using shift because some Vimeo embedded videos already map `S`, `D`, etc.).

**Comment by Jimbomon52** [comment] 2019-01-28 16:07
Having the same problem, and this is my most favorite Chrome extension.  It used to work just fine without going to full screen with every click on a control button.  Getting to be VERY FRUSTRATING and annoying!  Please fix this.  Thanks!

**Comment by joaoguilhermee** [comment] 2019-03-13 16:17
Same problem.

**Comment by truth1ness** [comment] 2019-03-16 21:40
They keyboard controls also cause the share and debug controls to open which is really annoying.

**Comment by truth1ness** [comment] 2019-03-16 21:43
You can also turn off key bindings in the Experimental Options menu now.

**Comment by himat** [comment] 2019-08-06 03:09
Is there any fix for this? Or a different chrome extension that works better?

**Comment by ChadBailey** [comment] 2020-03-26 20:12
I've tested this and am unable to reproduce. Is this still an issue or has it been resolved?

**Comment by bethrobson** [comment] 2020-03-26 21:13
Just tested it with Vimeo - still doing it. Thx. 
[Vimeo.mp4.zip](https://github.com/igrigorik/videospeed/files/4389957/Vimeo.mp4.zip)

**Comment by Jimbomon52** [comment] 2020-03-28 03:08
Just tested it with the videos on dd.darrenhardy.com <http://dd.darrenhardy.com/> site and it still goes full screen if clicking the + or - signs in the speed display.  But using the S and D keys to change the speed does NOT cause it to go full screen, but it causes the speed display to disappear and every other push of the S or D keys causes a box to pop up in the top left corner with a bunch of details.  Here’s a screen shot:

**Comment by ChadBailey** [comment] 2020-03-28 16:23
Replying to both of these comments: 
> Just tested it with Vimeo - still doing it
> it still goes full screen if clicking the + or - signs in the speed display.

I tested too, and unfortunately the problem is due to the mouse clicks being processed by a component underneath. If you intentionally click very slow it won't go fullscreen. I think I may be able to fix it by setting up a dummy listener on the controller which blocks propagation of events but I don't know if that will work. I'll give it a try

> using the S and D keys to change the speed does NOT cause it to go full screen, but it causes the speed display to disappear and every other push of the S or D keys causes a box to pop up in the top left corner with a bunch of details.

The problem with the stats showing up with hotkey usage is unfortunately related to the website choosing the same hotkeys for those stats. Fortunately, this can be fairly easily fixed in a couple of ways. One way is to reassign the keys to new keys that are not in use. Another way to fix is to click "Show experimental features" then select "Disable website keybindings" for the S and D keys.

**Comment by bethrobson** [comment] 2020-03-28 16:35
Thank you. I've gotten used to using the keys instead of the mouse on vimeo, just had to develop the habit. :-)

**Closed** 2020-05-17 16:35 UTC
Labels: bug
