### ISSUE TITLE
Extension for Chrome constantly needs to be repaired

### ISSUE THREAD

**Issue by JonB55198** [igrigorik/videospeed#492] opened 2019-07-10 04:40 UTC
Multiple times per day, the icon for Video Speed Controller disappears from the Google Chrome toolbar.  I then have to go into extensions and click "repair".  After this, all of my custom settings are lost.

**Comment by smaum** [comment] 2019-07-10 09:52
I haave the exact same issue. Extension keeps corrupting and needs to be repaired. Could it be an extension conflict?

Running: Win10Pro + Chrome 76.0.3809.46 (Official Build) beta (64-bit)

This has persisted now for weeks. I have tried disabling other extensions, but Videospeed still keeps getting corrupted and needs to be repaired.

**Comment by Eisys** [comment] 2019-07-10 12:17
Same here. Although less frequent. About once a week, maybe slightly more often.

**Comment by JonB55198** [comment] 2019-07-10 13:06
I'm Running:
Win 10 Pro & Chrome Version 76.0.3809.46 (Official Build) beta (64-bit)

**Comment by JonB55198** [comment] 2019-07-10 13:09
After more observation, it seems to be related to when the following happens:
+ a video on youtube is left paused in a tab
+ the tab is left to go to other tab or other programs
+ the computer is low on memory so the youtube video restarts when the tab is revisited.

I think it might have something to do with the process by which this video gets interrupted while Video Speed Controller is handling it.

**Comment by jacobcolbert** [comment] 2019-07-10 14:56
huh, i've never had this happen. How long has it been happening for each of you? Is the Errors button present in the box for it on chrome://extensions/ ? Or can you check the console on the tab you think caused the problem?

**Comment by Eisys** [comment] 2019-07-10 15:21
Started, I'd say, about 2-3 weeks ago maybe. I haven't thought to check for an Errors button but I'm pretty sure there isn't one. Just says it may have been corrupted and provides a Repair button in place of the toggle. I'm first hearing about it being reproducable so haven't checked console either but it happens so randomly to me that I don't think I'd catch it.

**Comment by jacobcolbert** [comment] 2019-07-10 21:25
Hmm. That really sucks. Sorry to all that are affected but this is out of my depth I fear since I have never seen it happen to anything. 

@igrigorik you have any ideas for what could cause it or how to try to determine the cause?

**Comment by rickyz** [comment] 2019-07-14 08:23
This is probably due to this Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=977805.

**Comment by igrigorik** [comment] 2019-07-14 23:36
Yikes. Never hit this one myself, hope the fix is rolled out soon.

**Comment by JonB55198** [comment] 2019-07-24 04:43
> Started, I'd say, about 2-3 weeks ago maybe. I haven't thought to check for an Errors button but I'm pretty sure there isn't one. Just says it may have been corrupted and provides a Repair button in place of the toggle. I'm first hearing about it being reproducable so haven't checked console either but it happens so randomly to me that I don't think I'd catch it.
> 
> EDIT: Just as I was done writing this I checked my extensions and this time [Poper Blocker has become corrupt.](https://i.imgur.com/PnxoGev.png)
> When VSC becomes corrupt it looks the exact same. So perhaps this isn't an issue with VSC alone.

Same here.  Started 3 weeks ago approximately.  There is no error button.  But in the chrome extensions page, it says "corrupt" and gives me the option to repair.

**Comment by JonB55198** [comment] 2019-07-24 04:46
> If you are running Chrome beta/dev/canary, then this is probably due to this Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=977805.

No.  I have not enabled the "Allow in incognito" for this or any other extension.  So this cannot be the case.

**Comment by naturallymitchell** [comment] 2019-08-10 15:07
Additional stability-related issues: #502 #498

**Comment by jacobcolbert** [comment] 2019-08-15 00:28
Seems the chromium bug cited above is in live and affecting more and more users. Hope they fix this soon, and hope it is the cause of this problem since I have no idea what is going on.

**Comment by Eisys** [comment] 2019-08-15 07:40
I'm on Beta Chrome and it hasn't happened to any addons in 2-3 weeks. So a fix is probably coming to live at some point

**Comment by igrigorik** [comment] 2019-08-15 17:15
\o/

**Comment by truth1ness** [comment] 2019-08-16 18:08
I'm getting this corruption issue all the time the last three days suddenly. I tried leaving incognito mode off and it still happened.

**Comment by Riseley** [comment] 2019-08-16 21:02
Running on normal Chrome on Linux, getting corruption every single time I open a new tab for the past week.

**Comment by joelsprechman** [comment] 2019-08-21 18:15
Hi. Love this extension but it has been very unreliable as of late.  Any updates here? This issue is occurring daily for me with 
the latest Google Chrome
Version 76.0.3809.100 (Official Build) (64-bit)

regular window, I'm not using incognito

thanks

**Comment by brunoedig** [comment] 2019-08-21 18:26
Same problem here. Every few days I need to repair it.

**Comment by fent** [comment] 2019-08-21 21:28
this kept happening to me, so I downloaded the extension and used Load Unpacked to install it. no longer happens. I have to manually update, but that's less annoying than having to fix it every couple of days

**Comment by jvschiavo** [comment] 2019-08-24 17:55
This happened twice with me recently. But only after I got the (late) update to Chrome v76 around August 20.

I think this is something with this version of Chrome, since it never happened with me before, and other extensions are having the same problem. Take a look: https://github.com/deanoemcke/thegreatsuspender/issues/988

Btw, I'm using Chrome OS (v76), my Samsung Chromebook 2 in particular got this update kind of late compared to the rest of Chrome users.

**Comment by jvschiavo** [comment] 2019-08-24 17:55
Are you all guys on Chrome 76, right?

**Comment by jvschiavo** [comment] 2019-08-24 18:08
For future reference, the message says: "This extension may have been corrupted."

Here it's what it looks like:
![image](https://user-images.githubusercontent.com/20977075/63641222-0fd1cf80-c681-11e9-80be-7a1d3502a578.png)

**Comment by joelsprechman** [comment] 2019-08-24 19:21
yes. Google Chrome is up to date Version 76.0.3809.100 (Official Build)
(64-bit)

**Comment by Xyrio** [comment] 2019-08-24 21:58
win7pro and chrome Version 76.0.3809.100 (Official Build) (64-bit) works perfectly. never seen this error but im mostly using it on youtube)

**Comment by rducottet** [comment] 2019-08-25 13:39
I have the same pb : "Multiple times per day, the icon for Video Speed Controller disappears from the Google Chrome toolbar." It  starded with the new Version 76.0.3809.100 of Chrome.
COuld you please resolve the pb ? Regards

**Comment by simon-olsen** [comment] 2019-09-03 01:07
Do I dare say it? (yes, obviously!)

All these extensions (except The Great Suspender) have one thing in common. They prevent, or provide the ability to skip, advertisements.

I can't help but be a little suspicious that this might be the result of intervention, rather than bugs in these extensions.

**Comment by sparanoid** [comment] 2019-09-03 10:21
One of the most frustrating things is that there's no way to export/import my custom settings when the extension corrupts all my custom settings/shortcuts lost.

**Comment by TiGR** [comment] 2019-09-06 12:00
@sparanoid Actually, you can keep your settings when extension goes "corrupt". Instead of fixing it via "chrome://extensions" and pressing button "repair" there, just go to chrome store and click "enable" there.

**Comment by lffg** [comment] 2019-09-07 17:18
I am also having this same issue. Happens every two days or something like that.

**Comment by Yatima-Kagurazaka** [comment] 2019-09-09 00:24
same here

**Comment by Ishaangandhi** [comment] 2019-09-09 05:07
I am also affected. Added https://chrome.google.com/webstore/detail/video-speed-controller

**Comment by Dithermaster** [comment] 2019-09-15 13:48
This is happening for me too. I'll repair it and it will work for a while, and then later it will not.

My extensions sync across Chrome on different machines, and my theory was that when I fix it on one machine, it breaks on another. But I don't see sync mentioned in the linked Chrome bug database, so that could be a red herring.

**Comment by larkwt96** [comment] 2019-09-16 01:39
Chrome is now on version 77. Maybe the bug has been fixed.

**Comment by Dithermaster** [comment] 2019-09-16 03:44
I'm on Chrome Version 76.0.3809.132 (Official Build) (64-bit) and it just happened again today. Does it say somewhere it's fixed in 77?

**Comment by albertbuchard** [comment] 2019-09-22 03:38
not fixed indeed..

**Comment by TiGR** [comment] 2019-09-22 07:23
@albertbuchard Are you using Chrome 77? For me extension works well since upgrade to 77.

**Comment by brunoinds** [comment] 2019-09-23 11:11
I'm using Google Chrome on MacOS X. And I saw the same error.

**Comment by achen88** [comment] 2019-09-25 20:39
@jacobcolbert I think this is caused by no `update_url` in the manifest.json -- there's no formal documentation for this but I did a google and repackaged the extension locally with this change; it hasn't broken for me yet. I can do a test later to see if removing this `update_url` causes it to corrupt itself again locally, but I'm pretty busy these days.

**Comment by jacobcolbert** [comment] 2019-09-25 20:51
> @jacobcolbert it hasn't broken for me yet. I can do a test later to see if removing this `update_url` causes it to corrupt itself again locally, but I'm pretty busy these days.

Thanks for the suggestion. If you (or anyone else) can do that, that would be great! I fear the fix for you may be due to no longer being downloaded from chrome store but instead sideloaded so would like to see evidence that is not the case.

**Comment by jacobcolbert** [comment] 2019-09-25 21:07
Are there any confirmed cases of people having the problem on chrome 77?

**Comment by jwsteiner** [comment] 2019-09-27 16:37
> Are there any confirmed cases of people having the problem on chrome 77?

I've been frustrated by this since August, but it hasn't occurred since I upgraded to Chrome 77 yesterday.  Hopeful that did the trick, but will be right back here to let you know if recurs...

**Comment by hellonearthis** [comment] 2019-09-27 18:57
Yeah, it seems stable to me too now.

**Comment by pcasaretto** [comment] 2019-09-30 14:53
I'm on Chrome 77 and had to repair it just now. It might have been broken since the last release. I'll update this thread if it happens again on this version.

**Comment by vultix** [comment] 2019-10-01 20:49
Can also confirm that this issue appears on Chrome 77

**Comment by achen88** [comment] 2019-10-01 20:58
@vultix I'm assuming it broke again after you upgraded to Chrome 77 and re-repaired?

**Comment by vultix** [comment] 2019-10-01 20:59
@achen88 Correct.

**Comment by lffg** [comment] 2019-10-01 21:35
I am also using Chrome 77 and the extension broke again.

**Comment by achen88** [comment] 2019-10-01 21:38
I'm not a maintainer, but my unofficial advice is: download and repackage the extension locally (this fixed the problem for me before Chrome 77).

**Comment by lffg** [comment] 2019-10-01 21:43
I am thinking in create my own version of this extension. This problem is annoying.

**Comment by jacobcolbert** [comment] 2019-10-02 00:02
This is terrible. I was really hoping it was solved in chrome 77. I agree that loading it as a package locally will almost certainly solve the issue. If you do go this route please check back for if it is resolved so you can get any updates! I still don't think this is a VSC problem per se though if anyone has any ideas please speak up!

**Comment by hellonearthis** [comment] 2019-10-02 00:19
Are people adding a lot of custom keys controls?
I had only 3 and no problems.  How many are you using if your having issues?
Google Chrome is Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by lffg** [comment] 2019-10-02 00:32
I am using the default controls and the problem exists still.

**Comment by jvschiavo** [comment] 2019-10-02 04:24
Since this probably started with Chrome v76 we should keep aware if other extensions are still suffering the same problem in v77. I personally don't have the issue anymore, it actually happened to me only a couple times in v76.

**Comment by jwsteiner** [comment] 2019-10-08 19:47
Quick update, I've gone 11 days without repairing since jumping to Chrome 77.

Customizations include speed change interval to 0.25 and preferred speed to 3.0x.  Also added one custom key, which is a preferred speed at 15x (I use "H", for "hyperspace"!)

Running on Windows 10 Pro v1809 build 17763.737

**Comment by derekju** [comment] 2019-10-17 23:33
I saw this all the time in Chrome 76 but since going to 77 things seem a little more stable. I don't remember the last time I had to manually repair so I'm hoping this is fixed. I use this plugin religiously.

**Comment by vapier** [comment] 2019-12-15 22:24
there were known bugs in Chrome itself related to extensions getting corrupted.  that should be resolved with the latest Chrome versions, so i'd just close this bug out.

**Comment by igrigorik** [comment] 2019-12-23 20:28
Resolving. Fingers crossed, hopefully the root problem is addressed.

**Closed by igrigorik** 2019-12-23 20:28 UTC
