### ISSUE TITLE
Amazon Prime or Netflix Streaming Videos?

### ISSUE THREAD

**Issue by ITJoePC** [igrigorik/videospeed#143] opened 2016-09-02 19:44 UTC
Is this made to work with Amazon Prime or Netflix?
I haven't researched it, but ff it's possible, I'd be interested in working on that piece.

**Comment by queuebit** [comment] 2016-09-02 19:51
It works on Netflix, Amazon Prime videos (although I often need to change the quality to SD to prevent buffering) and *some* Hulu videos.

It should work with HTML5 video.

**Comment by igrigorik** [comment] 2016-09-16 02:59
> Thanks, yes, I just noticed it's working in Amazon Prime. Except, I can't click on it, but the key controls seem to work.

Yep, that's a dupe of https://github.com/igrigorik/videospeed/issues/134 -- let's continue this discussion there.

**Closed by igrigorik** 2016-09-16 02:59 UTC
