### ISSUE TITLE
Keyboard controls not working in fullscreen?

### ISSUE THREAD

**Issue by Reagankm** [igrigorik/videospeed#54] opened 2015-07-25 20:01 UTC
Hi.

This used to work just fine (last time I used it was about three weeks ago) but today when I'm watching a Netflix video in fullscreen the keyboard speed up and slow down keys do not respond.  It still shows the current speed in the corner as if the plugin were active.  If I hit escape to back out of fullscreen and continue watching within the browser then I can use the keyboard controls.

If I go to Chrome's View menu and choose to make Chrome fullscreen, then it works.  For some reason it's just Netflix's fullscreen control that is making it behave oddly.

I'm using Google Chrome Version 43.0.2357.134 (64-bit) running in Ubuntu 15.04

**Comment by igrigorik** [comment] 2015-07-26 20:34
Odd. Don't have access to a Netflix account to test.. Tried fullscreen on YouTube and few other HTML5 players and everything seems to be working as expected.

**Comment by igrigorik** [comment] 2015-11-07 20:29
Closing, can't reproduce. Let me know if this still an issue once 0.2.6 is released.

**Closed by igrigorik** 2015-11-07 20:29 UTC

**Comment by batterseapower** [comment] 2016-01-31 09:05
It still doesn't work in 0.2.6. The problem is that the document keypress event handler you install is not being called when the video is fullscreen. Apparently this is intentional behaviour: http://stackoverflow.com/questions/22646541/html5-video-detect-keypress-in-full-screen-mode

What's weird is that keypress does fire for *most* keys with fullscreen Youtube, including the s and k keys. However, Chrome doesn't fire keypress for fullscreen Youtube for e.g. the 'a' key. WTF?

Even stranger, the keyup event seems to work perfectly in fullscreen on both sites. Maybe you could switch to using event instead?

(I'm using Chrome 47.0.2526.111)

**Comment by igrigorik** [comment] 2016-02-01 05:52
@batterseapower interesting, I'll investigate.. In the meantime, you can customize your keys in the plugin options panel.
