### ISSUE TITLE
Controls have disappeared on all sites

### ISSUE THREAD

**Issue by rik130** [igrigorik/videospeed#502] opened 2019-08-08 12:01 UTC
Since 24 hours ago the controls have disappeared and no amount of changing/refreshing/reinstalling brings them back.  Flash is allowed in Chrome as per normal.  Nothing changed with my system.  Please fix this ASAP!

**Comment by naturallymitchell** [comment] 2019-08-10 15:04
Probably related to #498 

---

> Please fix this ASAP!

Dude...  ease up a bit.

**Comment by ice1080** [comment] 2019-08-19 03:02
Not sure if this is related or not, but mine keeps getting disabled in Chrome. I have to go back to the extension page and it then tells me that the extension has been disabled and asks if I want to re-enable it.

Chrome version 76.0.3809.100
OS Version Ubuntu 18.04.3 LTS

I have also seen this in the same chrome version within Mac OS Mojave V10.14.6

**Comment by hellonearthis** [comment] 2019-08-19 03:17
I've been getting extension corruption too and have to repair and adjust settings..

**Comment by sschaer** [comment] 2019-08-22 15:13
same on mac with version 0.5.7 .. no controls anymore, shortcuts don't work :( 

PLEASE FIX ASAP OR I WILL CONTINUE SCREAMING INTO THE VOID ;) 
jk.. thanks for the extension though .. hope it gets fixed soon again.
I've been using it so often now that I forgot that it is an extension at all (had to look it up when it stopped working :) )

**Comment by alon91** [comment] 2019-08-22 16:53
I have something that may be related: on two of my machines (one Chrome OS, one OS X) I've gotten a "This extension may have been corrupted" error. First time I've ever seen this:

![image](https://user-images.githubusercontent.com/35006176/63533700-2ed63300-c4c2-11e9-8619-b6e27322678d.png)

When I hit the "Repair" button I get the following pop-up:

![image](https://user-images.githubusercontent.com/35006176/63533791-5cbb7780-c4c2-11e9-963f-bc7b7110cf75.png)

Extension then gets reinstalled, with all its previous settings (keyboard shortcuts, blacklist, etc.) having been reset. Seems to work well afterwards! Not sure if this will get corrupted again.

I love VSC! Thanks for this excellent add-on!

**Comment by jvschiavo** [comment] 2019-08-24 18:18
> Probably related to #498
> 
> > Please fix this ASAP!
> 
> Dude... ease up a bit.

More probably a duplicate of https://github.com/igrigorik/videospeed/issues/492

**Comment by jacobcolbert** [comment] 2019-09-25 20:00
dupe. still don't know how to fix and hope it is the chrome bug

**Closed by jacobcolbert** 2019-09-25 20:00 UTC
