### ISSUE TITLE
Controls are not showing up for vimeo videos

### ISSUE THREAD

**Issue by jakhay** [igrigorik/videospeed#575] opened 2020-01-08 22:13 UTC
Controls are not showing up for vimeo videos

Tried firefox and chrome on mac.

**Comment by igrigorik** [comment] 2020-01-09 04:42
I believe this is a dupe of https://github.com/igrigorik/videospeed/issues/572, please reopen if this is still an issue with 0.5.9.

**Closed by igrigorik** 2020-01-09 04:42 UTC

**Comment by jakhay** [comment] 2020-01-09 16:36
Webstore (and chrome) still show version 0.5.8, although the update date (on Chrome webstore) shows Jan 8.
Controls now show up in Vimeo, but are not responding to mouseover or mouse clicks.

**Comment by jakhay** [comment] 2020-01-09 16:38
Comments added. Did not see a way to “reopen” this one.

Thanks for looking into this!
