### ISSUE TITLE
Prevent mouse click event from bubbling up to video container

### ISSUE THREAD

**Issue by anhnhoktvn** [igrigorik/videospeed#512] opened 2019-09-10 05:53 UTC
When I click on the controller (the extension), it often pauses the video. I think you could add a `stopPropagation` call to prevent this.

**Comment by jacobcolbert** [comment] 2019-09-25 20:09
This should be fixable, but I have never run into the issue myself since i never use the overlay. Can you give me an example video I can test against?

**Comment by anhnhoktvn** [comment] 2019-09-26 01:18
For example, in vimeo, it'll enter fullscreen mode when you click on the overlay. [https://vimeo.com/357762214](https://vimeo.com/357762214)

**Comment by jacobcolbert** [comment] 2019-09-26 05:21
Got it thank you. Fix for the button press is trivial like you said, but it
messes up the dragging which i've never looked at yet. shouldn't be too
hard to get around.

**Comment by thewheat** [comment] 2019-10-05 08:03
Based on https://github.com/igrigorik/videospeed/issues/512#issuecomment-535287202 this issue seems like the root cause of https://github.com/igrigorik/videospeed/issues/425

**Comment by igrigorik** [comment] 2020-09-12 20:23
I believe this should be resolved via #635.

**Closed by igrigorik** 2020-09-12 20:23 UTC
Labels: enhancement
