### ISSUE TITLE
"This extension may have been corrupted"

### ISSUE THREAD

**Issue by bchansan** [igrigorik/videospeed#508] opened 2019-08-29 23:56 UTC
Getting the above message on Chrome since updating my OS. Message reappears after 12-24 hours of use. Resolved with "Repair" or with reinstallation. 

Chrome: Version 76.0.3809.100 (Official Build) (64-bit)
macOS Mojave Version 10.14.5 

Please let me know how to proceed.

**Comment by Eisys** [comment] 2019-08-30 09:55
Duplicate of #492

Nothing to do on your end. It's a problem with Chrome 76 so gotta wait til Chrome fixes the bug, this is not caused by VSC.

I'm on Chrome beta 77 and it hasn't happened since the 77 update.

**Comment by alicansoysal** [comment] 2019-09-03 10:27
The problem still exists on 77. What type of bug is it? Are you sure?

**Comment by Benu-Athanasia** [comment] 2019-09-08 17:12
It's obnoxious, but a super simple fix. Repair takes all of two seconds and works like a charm.

**Closed** 2019-09-23 15:11 UTC

**Comment by alon91** [comment] 2019-10-12 21:39
> It's obnoxious, but a super simple fix. Repair takes all of two seconds and works like a charm.

Except that I customize all keyboard shortcuts, speed increments, etc. so the fix takes more like 1 minutes. Not end of world but annoying. I've started following #492 -- hope there's some solution for this eventually!
