### ISSUE TITLE
Video playback speed reseting to 1.0 whenever I pause/play

### ISSUE THREAD

**Issue by nora191star** [igrigorik/videospeed#587] opened 2020-02-09 15:38 UTC
Hello!

I am having an issue where whenever I hit pause/play on a video, the playback speed resets to 1.0 and I have to manually increase the speed again every time. This becomes a hassle when watching lectures. The problem seems to be Mediasite.com overriding the controls but I have zero background on coding to know how to fix this.

I have seen a few other resolved tickets related to this issue but unfortunately they all seem to be for Echo360. (i.e. https://github.com/igrigorik/videospeed/issues/459) 

Is there anyway that I could stop this from happening? I love this extension and have no issue with it on any other site. 

Also if a patch is created, how exactly do I add it to my extension? (again, total coding noob)

Thank you!

**Comment by ChadBailey** [comment] 2020-02-18 03:50
Thanks for your report. and sorry for taking so long to respond.

I'll start with the easy answer... if a patch is created, it's automatically pushed out to you once we update the extension in the web store, so no need to do anything special. If you were to feel so inclined to try it ahead of it being pushed out to the entire world, you could do that by installing it locally following the contribution guide in CONTRIBUTING.md but that's not necessary.

Now for the harder one... It's likely the event tied to play/pause also applies the playback rate. I'm not sure why that design pattern would be used, but none the less that seems like the root cause. Anything I or anyone else would say to this would be pure speculation though, as we are unable to test. Is there a video we can play for testing this out? The front page doesn't appear to have this behavior, so I assume the lectures are using different code.

**Comment by nora191star** [comment] 2020-02-18 16:36
Hello! If a patch is created I will definitely be patient and just wait for the update.

Below is a link to a video of what's occurring. I'd provide a link to a lecture but unfortunately they are only visible with our student accounts. As you can see, MediaSite's playback speed overrides the extension every time the video is paused. What I have noticed is that if I increase MediaSite to 1.6x for example, then every time I pause and play, it'll return to that speed instead of 1.0. So it's definitely their program overriding the extension. 


https://imgur.com/a/23Z89vT

**Comment by ChadBailey** [comment] 2020-03-02 04:27
This MIGHT be fixed with #604. Once it gets merged in and pushed out to the world I'll have you test out to see if it was fixed.

**Comment by ChadBailey** [comment] 2020-03-26 18:43
The fixes were merged in version 0.6.1, can I have you try and validate this has been fixed?

**Closed** 2020-09-12 20:27 UTC
Labels: Work Complete, blocked:feedback
