### ISSUE TITLE
When I play Udemy video, click pause and the playback speed is automatically reset to 1.0

### ISSUE THREAD

**Issue by liaoleejun** [igrigorik/videospeed#238] opened 2017-07-08 02:17 UTC
**System and video speed controller version:**

- Windows 10
- Chrome 59.0.3071.115
- https://www.udemy.com/
- Video Speed Controller 0.4.8

**Steps to reproduce:**

1. Open a Udemy video.
2. Click icon and change speed. (Change to 1.20, for example)
3. Pause the video.
4. Continue to play the video.
5. Then speed will be reset to 1.00.

**Expected behavior:**
Speed keeps to be 1.20 (the set value)

**Actual behavior:**
Speed shown in the icon is 1.00, and actual play speed is reset to 1.00.

**How often does this happen?**
Always

**Comment by igrigorik** [comment] 2017-08-27 18:25
@liaoleejun thanks for the detailed report -- wish every report was as helpful!

Debugging the logic on their site (using a [free course](https://www.udemy.com/learn-ruby-on-rails-from-scratch/)), it looks like the issue is that their player is overriding settings when playback starts. Specifically: VSC can update speed while the video is playing, and persists updated speed into extension settings successfully. However, Udemy has own preference which it applies whenever playback starts -- as a result, the speed is reset.

Unfortunately I don't think there is anything we can do here on our end.. as there is no way for the plugin to override site+player defaults. The right behavior here would be for Udemy to also listen to ratechange events and update their preference. 

Closing this with no action, as we can't fix it on this end.. However, if you're up for it, might be worth pinging them with a feature request.

**Closed by igrigorik** 2017-08-27 18:25 UTC

**Comment by gitnix** [comment] 2017-09-14 14:47
Hey @liaoleejun  I love this extension for youtube videos and such and was also sad to discover it didn't work with the Udemy site. I contacted Udemy as @igrigorik suggested regarding playback speed and ratechange events. They said they would forward the message to the devs. This spurred me to put together something to fill the gap and for anyone visiting this thread, I made a [chrome extension](https://chrome.google.com/webstore/detail/udemy-video-playback-spee/jipobffkabkgddgmdmmgjoaopbnjnffn) that let's you watch Udemy videos with .25 speed increments at up to 3.5x speed. It integrates with the native UI on the site. Here is a [link to the repo](https://github.com/gitnix/chrome-extension-udemy-playback-rate)

**Comment by mariusi7** [comment] 2017-09-24 08:45
I have the same problem for a while on HBOGO, but it resets to 1.00 anytime in the first few minutes of opening the video (not just on Pause). Most times I can make it work if I wait "long enough" (5 min) and only later change the speed. So I assume it has to do with buffering / video not loaded yet.. 
If so, @igrigorik can't this be detected by the extension and either try to keep sending events to change the speed to "Preferred" every X seconds ? Or detect the event of video fully loaded and set it to the preferred one if current speed = 1.00?
Unfortunately I can't contact them and hope they adapt the player (it's not theirs). So I'm looking for any workaround to that. It's interesting how @gitnix extension did work for udemy, maybe he can explain and if smth similar is usable for other sites like Udemy or hbogo

**Comment by HarleyGolfGuy** [comment] 2018-05-30 21:18
@mariusi7 For HBOGO you want to slow it down.  Winter is coming!  You don't want what's beyond the wall to go any faster than 1.00 speed.  ;)

**Comment by minh-nguyen-iress** [comment] 2023-05-03 13:10
I came across this thread when I was searching for the playback speed not remembered on Udemy. It turned out that in the options of the Video Speed Controller extension, you can specify the sites where the extension is disabled. Disabling it will let the Udemy speed control works and it will remember the speed between lessons.

**Comment by h3x311** [comment] 2024-05-13 17:32
Thanks @minh-nguyen-iress You made my day!

**Comment by halil-akgun** [comment] 2024-11-15 21:57
Thanks @minh-nguyen-iress
