### ISSUE TITLE
not working on netflix

### ISSUE THREAD

**Issue by ankoyaki** [igrigorik/videospeed#317] opened 2018-02-26 02:26 UTC
the controls disappeared from netflix and pressing D doesnt work either

**Comment by igrigorik** [comment] 2018-02-26 02:29
Do you see controls on other sites, like YouTube.com?

**Comment by ankoyaki** [comment] 2018-02-26 02:30
yes!

**Comment by igrigorik** [comment] 2018-02-26 02:35
Odd, I can't reproduce this behavior on Netflix: controls showing up fine on this end.

**Comment by jesslataree** [comment] 2018-02-27 23:01
Hi! I have another question about using your plugin with Netflix. All the speed commands work fine and I can see the controls and everything BUT... when I try using the Rewind and Advance commands, I get an error message from Netflix (error M7375) and then I have to reload the whole page. Any idea on how to fix that?

**Comment by igrigorik** [comment] 2018-03-04 05:28
@jesslataree see https://github.com/igrigorik/videospeed/issues/260 - bug on Netflix side.

@ankoyaki I can't reproduce the issue on this end; I see controls showing up on Netflix. If you see controls on other sides, my only other guess would be.. corp policy? See https://github.com/igrigorik/videospeed/issues/310 — it's possible that your policy prohibits the extension from running on Netflix.

I'm closing this with no action, if you find more clues please feel free to reopen.

**Closed by igrigorik** 2018-03-04 05:28 UTC
