### ISSUE TITLE
The controller is not clickable on Amazon Prime

### ISSUE THREAD

**Issue by mariusi7** [igrigorik/videospeed#486] opened 2019-06-09 06:59 UTC
The keys work but I can't click the controller to change speed. Left click pauses the video.
Normally not a big problem, but I use just the mouse while watching the monitor from 3-4 meters away.
There's no experimental feature to override this, just for keys... 
https://i.imgur.com/HYjR6Dj.png

Also tried with latest code from master, same problem. 
Anyone else has this ?

**Comment by bandit789** [comment] 2019-06-13 15:04
as a workaroundi use a little program autohotkey https://www.autohotkey.com/

and made a .ahk file with this inside:

`SetTitleMatchMode, 2

#ifWinActive, Chrome
MButton & WheelUp::Send, d
MButton & WheelDown::Send, s
Rbutton::
;
;it gives you half a second to either complete the double click
;or to complete the press-and-hold cycle. If neither happens
;you get a normal single click response.
;
keywait, rbutton, t0.5
if errorlevel = 1
{
;
;This registers a 'press-n-hold' on the right mouse button.
;ADD YOUR FUNCTIONS HERE, for instance
;you could do a control-n to open a new IE window, as below
;
send, g
return
}
else
keywait, rbutton, d, t0.5
if errorlevel = 0
{
;
;this registers a 'double click' on the right mouse button.
;add your functions here, for instance I use it below
;to do a shift-left click which opens a link in its own window
;
send, x
return
}
else 
;
;if neither of the above heppen, send a regular single click
;
mouseclick, right
return
#ifWinActive`

use script without the ' ' qoutes on the beginning and ending.
If you press and hold the scrollwheel and turn up it does +0.1 per click and if you turn back it does -0.1

also holding left button sets prefered speed.

**Comment by jacobcolbert** [comment] 2019-10-02 00:04
> The keys work but I can't click the controller to change speed. Left click pauses the video.

Do you still have this issue? I cannot reproduce.

**Comment by hellonearthis** [comment] 2019-10-02 00:11
I see the current speed displayed but mouseover doesn't give me the controls.
I use the keys to adjust speed and don't mind doing that.
<img width="628" alt="Screenshot_61" src="https://user-images.githubusercontent.com/121805/66009203-f0e31a80-e515-11e9-8af2-80d856a4d42b.png">

**Comment by mariusi7** [comment] 2019-10-02 08:53
Yes, still have it. It's like hellonearthis is also saying, the mouse doesn't give you the controls. Left click pauses, you have to use the keyboard as a workaround. It's a minor inconvenience though

**Comment by igrigorik** [comment] 2019-12-23 20:32
Looks to be a-ok now on this end. Resolving. If it's still an issue, please reopen.

**Closed by igrigorik** 2019-12-23 20:32 UTC
