### ISSUE TITLE
Reset speed value not remembered after pause

### ISSUE THREAD

**Issue by sharkistani3awtani** [igrigorik/videospeed#413] opened 2018-12-25 15:51 UTC
To better explain the issue I will give an example (click means hitting shortcut key): 
I set Preferred Speed = 2x => I watch a video with speed = 1.5x => I click on reset speed (Speed = 1x) => I click pause (speed = 0x) => I click pause again (speed = 1x) => I click on Reset Speed (Speed = 2x instead of 1.5x)

**Comment by Eisys** [comment] 2018-12-27 16:41
Can confirm. As I already commented on another post..

**Comment by igrigorik** [comment] 2019-02-20 18:59
Thanks for reporting. Duplicate of #428, let's continue there.

**Closed by igrigorik** 2019-02-20 18:59 UTC
