### ISSUE TITLE
When watching videos in general  with or without speeding up the vid I get this...

### ISSUE THREAD

**Issue by throwaway2342** [igrigorik/videospeed#316] opened 2018-02-23 09:03 UTC
I have to explain what I am saying so here it is....lets say I am watching a video on youtube......when I am watching....the video screen will flash every few seconds...usually it will be a black screen or sometimes white.......but the point is the main bug is that. 

I have chrome and I am using mac as my OS....everything is updated to its full. 

Everything should run fine tbh, but I keep getting this error, the best way to get rid of it is by reloading the page but its honestly really annoying. Can you fix ?

**Comment by fent** [comment] 2018-02-23 14:26
I get this too, it's pretty rare though. It also happens on sites where I have videspeed disabled, so I'm not too sure that this is the cause.

A better temporary solution to fixing it when it happens: pause the video, then scroll the page down, then back up to the video, and play it.

**Comment by igrigorik** [comment] 2018-02-23 16:39
I've seen same behavior but haven't been able to reliably reproduce or figure out why it happens; not clear if VideoSpeed is the culprit.

**Comment by canarslan12** [comment] 2018-03-10 15:33
I have green screen issue rarely, I think it's because read/write speed (of GPU) can't catch video speed. Maybe something about GPU driver can fix this(reveting to older version) and it's irrelevant to extension

**Comment by igrigorik** [comment] 2018-04-01 20:28
Closing, as I can't reproduce this.. If you guys can, please reopen, so we can debug and fix it.

**Closed by igrigorik** 2018-04-01 20:28 UTC
