### ISSUE TITLE
YouTube video is high pitched after being paused for a minute

### ISSUE THREAD

**Issue by electro928** [igrigorik/videospeed#308] opened 2018-01-27 23:06 UTC
Whenever I leave a YouTube video paused for around a minute the video becomes high pitched and fast after I resume. I have to refresh the page every time this happens.

**Comment by canarslan12** [comment] 2018-02-08 10:38
Which version of Chrome you're using?
Because it feel like video engine problem and has to be fixed by Chrome.

**Comment by igrigorik** [comment] 2018-03-04 05:29
@electro928 if the problem is still there please file a bug on crbug.com.

**Closed by igrigorik** 2018-03-04 05:29 UTC
