### ISSUE TITLE
No longer works with YouTube?

### ISSUE THREAD

**Issue by carneggio** [igrigorik/videospeed#310] opened 2018-02-08 23:01 UTC
As of today the speed controls no longer work on YouTube for me - does this happen for anyone else? I'm using Chrome 64.0.3282.14. I already deinstalled and installed video speed controller again. It works fine on vimeo, netflix, etc. but when I go on YouTube, the videos respond to none of the regular controls, nor can I pop up the video speed icons. YouTube isn't whitelisted, so that is not the issue. Anyone else, or just me?

**Comment by EugenHotaj** [comment] 2018-02-09 02:38
I'm seeing the same issue. It seems that YouTube updated some things (noticed some new icons I've never seen before). Adblocker also seems to be broken.

**Comment by carneggio** [comment] 2018-02-09 10:17
Yeah, my uBlock origin broke as well. It would be great if videospeed could be updated/fixed - I'd rather watch my videos at the correct speed, with ads, than the other way around!

**Comment by wesbos** [comment] 2018-02-09 15:53
I can confirm that if you turn uBlock off, this extension works fine.

So maybe not an issue with this extension, but uBlock?

**Comment by EugenHotaj** [comment] 2018-02-09 16:19
I'm not using uBlock, but AdBlockPlus [1]. I tried disabling it but this extension still doesn't work. 

[1] https://adblockplus.org/

**Comment by weirdesky** [comment] 2018-02-09 19:28
This is also true for me, but is only true on some of my devices.  In particular, my linux machine (my chromebook works fine): Version 64.0.3282.140 (Official Build) (64-bit).  I can't confirm with all of my extensions disabled (it's a corp machine, so it has some un-removable extensions), but it does persist even after uninstalling uBlock.

**Comment by adiknoth** [comment] 2018-02-10 13:08
I'm also affected, both OSX and Linux. Only on YouTube, all other sites like FB or vimeo are fine. uBlock on/off doesn't make a difference for me.

I have at least one OSX device where it works, but maybe it was a gradual rollout on YT's end.

I've noticed that the videospeed controller goes into "top" on FB and vimeo, but ends up in "ads" or "iframe.html" on YT now:

YT:
![image](https://user-images.githubusercontent.com/1333665/36062356-26070baa-0e6b-11e8-95ff-e17eb2030c1f.png)

Vimeo: 
![image](https://user-images.githubusercontent.com/1333665/36062381-b4acd33a-0e6b-11e8-87b0-74ad0ff2e31d.png)

**Comment by igrigorik** [comment] 2018-02-10 19:43
Hey folks, thanks for the reports. I'm puzzled by this one and still trying to figure out what's going on here.. As far as I can tell, this is not related to any cross-extensions bugs or interop problems. Rather, it looks like the content script is simply not being injected into the page for some (???) reason.

I'm testing in Version 64.0.3282.140 with and without other extensions.

If you have any leads, lmk.

**Comment by EugenHotaj** [comment] 2018-02-15 01:11
This doesn't seem to effect Firefox, and (as pointed in the bug) seems to only effect chrome browsers that are managed by corp admins.

**Comment by windsifter** [comment] 2018-02-17 01:14
Have a chrome browser managed by corp admins, and VideoSpeen no longer works on my Mac, but works fine on my Chromebook. Both with latest OS / Chrome versions.

**Comment by igrigorik** [comment] 2018-02-17 16:57
Hi folks. 

We've narrowed this down to [corp-policy rollouts](https://support.google.com/chrome/a/answer/7517624?hl=en&ref_topic=7517516). There is nothing wrong with the extension itself. Rather, Chrome recently enabled support for extension policies and it looks like — not surprisingly — a number of organizations have started using it. You can inspect if a policy is active on your profile via:

- chrome://policy
- Under ExtensionSettings > show value
  - "runtime_blocked_hosts" contains list of origins on which extensions may be blocked
- Alternatively, only certain extensions could be whitelisted

As such, we're obviously not in a position to do anything about the policy or the fact that extension is not executed. Well, other then go talk to your policy folks and convince them that they can audit source of this extension and (hopefully) whitelist it. 

The related meta issue here is that there are no clear user or developer signals that a policy prevented an extension from executing. For that, see [crbug.com/811968](https://crbug.com/811968) and chime in if you have any suggestions.

---

I'm closing this bug, because there is no action on our side: extensions can't introspect the policy or do anything if policy prevents them from executing.

**Closed by igrigorik** 2018-02-17 16:57 UTC
