### ISSUE TITLE
"Decrease speed" is making the video go back by 15 or more minutes

### ISSUE THREAD

**Issue by Reagankm** [igrigorik/videospeed#257] opened 2017-09-02 03:43 UTC
As of today (first time I've noticed it and I used this at least 2 days ago and possibly yesterday without issue), in Netflix if I hit "s" (the key I have attached to "Decrease speed") it refreshes the video and moves it back by over 15 minutes.

It's driving me crazy. Let me know how to include any relevant logs and I'll be happy to do so. I'm on OS X 10.12.6 and Chrome 60.0.3112.101

**Comment by igrigorik** [comment] 2017-09-02 05:34
Hmm, I can't reproduce this behavior. 

a) Any other extensions you installed, that could be conflicting or hijacking the key?
b) Check your plugin configuration settings: you can customize the keys there, did you change those by any chance?

**Comment by igrigorik** [comment] 2017-09-16 16:12
Closing, please reopen if its still a problem / you can provide more info on how to reproduce.

**Closed by igrigorik** 2017-09-16 16:12 UTC
