### ISSUE TITLE
Not working with Imagus anymore.

### ISSUE THREAD

**Issue by Eisys** [igrigorik/videospeed#627] opened 2020-03-29 13:30 UTC
Before the latest update, the controller showed up on the popup picture/video.
Not so anymore.

Useless on pictures so that's a good thing but on videos it should work.

Previously when the controller showed up, VSC's shortcuts worked on hovered videos but that's also gone.
But if I, prior to using hover, watch a video at 2x speed, then the hover video still plays at 2x, I just can't change that in any way. So the only thing still working is 'remember playback speed'

Imagus has its own speed control but that uses 2 key presses which is annoying and has no indicator how fast the video actually is. So at the very least the controller should show up indicating speed.

But since this is a problem with a function of a seperate addon and not default behaviour, the priority on fixing this(if at all) should be low.

**Comment by ChadBailey** [comment] 2020-03-30 00:39
I don't have any good way of testing this, but think this may be a duplicate of #609. I think it may be a good time to push the current branch as a hotfix release of 0.6.2... I'll let you know when to re-test

**Comment by s-i-m-s** [comment] 2020-06-12 23:29
I'm also seeing this issue.

**Comment by igrigorik** [comment] 2020-09-12 15:38
Please reopen if this is still an issue with latest version.

**Closed by igrigorik** 2020-09-12 15:38 UTC
