### ISSUE TITLE
"Invalid Url" on S key.  

### ISSUE THREAD

**Issue by zfreeds** [igrigorik/videospeed#226] opened 2017-06-11 14:01 UTC
Sometimes pressing the "S" key to slow down the video will open a dialog saying "Invalid Url (".  This problem will continue to occur until the page is reloaded.

**Comment by igrigorik** [comment] 2017-06-11 15:40
Is this happening on a particular site?

**Comment by igrigorik** [comment] 2017-06-25 19:06
Closing as I can't reproduce, please reopen if you have a particular example we can debug.

**Closed by igrigorik** 2017-06-25 19:06 UTC

**Comment by zfreeds** [comment] 2017-07-10 02:36
@igrigorik .  I'm sorry for the very late reply.  My github notifications seem to be broken.  I would say this happens usually on Youtube but that could just be because most videos I watch are on Youtube.  I still cannot give proper steps to reproduce as it happens randomly.  If I ever figure out the steps, I shall let you know

**Comment by Steve-357** [comment] 2019-02-23 01:56
This is happening to me on YouTube, on a variety of videos and channels.  Windows 10 Pro, 64-bit, latest release of Chrome.  I do use Diigo, and the "capture" button for Diigo appears close enough to the speed control that I can't adjust the speed from there.
