### ISSUE TITLE
Speed repeatedly drops to 0.00

### ISSUE THREAD

**Issue by Benu-Athanasia** [igrigorik/videospeed#510] opened 2019-09-08 17:15 UTC
As the title says, the speed keeps suddenly jumping down to 0.00 every 5 minutes or so. So far I'm seeing this on HBO GO and VRV.

It's more of a nuisance than anything, but HBO is seeing it as a streaming error and giving me this every few times it drops, "Can’t Play Video We’re having trouble playing this video. Please try again later."

I *think* it might be connected into the commercial breaks somehow. At least that's how it looked on VRV. Not sure about HBO GO since I'm really new to both sites.

**Comment by Benu-Athanasia** [comment] 2019-09-15 18:07
Disneynow is now doing it as well.

**Comment by igrigorik** [comment] 2019-12-23 20:27
I believe this should have been addressed in one of previous releases. Closing, please reopen if the problem is still there.

**Comment by Benu-Athanasia** [comment] 2019-12-23 21:18
Nope. Error is still there and has spread to Disney Now.

**Comment by igrigorik** [comment] 2019-12-23 23:21
Hmm. Do you have any public test URLs?

**Comment by Benu-Athanasia** [comment] 2019-12-24 18:29
Do you mean the url to a video I've encountered this problem on? Because it's done it several times on this video despite my download speed being 56 mbps
[https://disneynow.com/shows/star-wars-resistance/season-02/episode-12-212/vdka15054931]

**Comment by ChadBailey** [comment] 2020-02-18 04:49
I have tested this URL and it is working as expected. Can you confirm if it's fixed?

**Comment by ChadBailey** [comment] 2020-02-28 14:48
Going to close this for now, please reopen if you're still experiencing a problem.

**Closed by ChadBailey** 2020-02-28 14:48 UTC
Labels: blocked:feedback, bug
