### ISSUE TITLE
Minor Youtube annotation problem.

### ISSUE THREAD

**Issue by Eisys** [igrigorik/videospeed#151] opened 2016-10-12 00:58 UTC
For a little while now, I have noticed that there are issues with Youtube's annotations. They appear too late and stick around for too long.
And it's worse the faster the speed.

Setting the speed back to 1x or disabling the extension fixes it.
I watch most videos at 2x. If I have the extension disabled and just set the youtube player's own speed to 2x then this problem doesn't happen.

I don't know if this is something that you could even fix but thought I'd let you know.

And I wanted to ask something; Is there a possibility of you making a userscript version? That way more people could use it.

**Comment by fent** [comment] 2016-10-12 01:12
YouTube already has this option in its own player controls.

**Comment by igrigorik** [comment] 2016-10-20 21:28
I can't reproduce this. Subtitles are correctly synced, regardless of playback speed, on this end.. In fact, I remember filing a bug for this a while back with YT team, and they fixed it pretty quickly. Is there a particular video where you see this problem? Also, as @fent mentioned, you _can_ disable them via existing YT controls if you don't want to see them.

> And I wanted to ask something; Is there a possibility of you making a userscript version? That way more people could use it.

No such plans currently.

**Comment by Eisys** [comment] 2016-10-20 21:54
Subtitles work fine. I know that. 
It's the annotations and the new end cards that have problems. The timing on them is off.

I watch videos at 2x speed and for a week or 2 now, annotations and end cards don't appear at correct times until I pause the video, which sort of resets them I guess. Then they appear.

**Comment by igrigorik** [comment] 2016-10-20 23:26
@Eisys doh! Sorry, confused subtitles with annotations. I can reproduce the problem now.. Filed a bug (internal) with the YouTube team. Unfortunately I don't think this is anything we can fix on our end, I'm hoping they'll roll out a fix soon.

Closing in the meantime, since this is a noop on this end.

**Closed by igrigorik** 2016-10-20 23:26 UTC
