### ISSUE TITLE
Alternative sortcuts

### ISSUE THREAD

**Issue by Plus200** [igrigorik/videospeed#38] opened 2015-04-12 06:28 UTC
I’m using more than one keyboard layout (English/Hebrew/Russian/Arabic), so when I search YouTube in one of the other languages, the shortcuts do not work.

If you could add additional alternative layout for each of the actions, it would be most helpful, I’ll then just add the equivalent to the A-S-D keystrokes on the other layouts.

Thank you!

**Comment by igrigorik** [comment] 2015-05-18 15:36
@Plus200 thanks for the feedback. It seems that adding multiple shortcut keys per action will quickly get out of control.. and the problem is, the library does not know your current layout. I'm inclined to mark this as wontfix.

**Closed** 2015-06-02 05:45 UTC
