### ISSUE TITLE
video control panel disappears on Win + touchpad

### ISSUE THREAD

**Issue by evodoc** [igrigorik/videospeed#213] opened 2017-05-14 13:25 UTC
This was reported and fixed once already but it's happening again:
I open a youtube video which has 1.00 speed by default.
I keep pressing the increase speed button.
By the time I reach ~1.75, the control panel hides while I'm still clicking, which means I pause the video by accident.

Actually that was the original issue, but nowadays it happens even more frequent.

**Comment by igrigorik** [comment] 2017-05-15 01:58
I can't reproduce this behavior with latest Chrome + plugin version. Are you running the latest versions? The controller does auto-hide after a period of inactivity, but every clicks resets that timer..

**Comment by evodoc** [comment] 2017-05-15 08:04
Chrome 58.0.3029.110 (64-bit) + Video Speed Controller 0.4.7
I also tried disabling other plugins.

**Comment by igrigorik** [comment] 2017-05-15 14:48
Hmm -- odd. If I could replicate it, we could fix it.. Can you record a screencast?

**Comment by evodoc** [comment] 2017-05-15 15:47
Here: https://www.youtube.com/watch?v=9pRLsWTxVUQ
It happens twice.

**Comment by igrigorik** [comment] 2017-05-16 21:45
Interesting. I can't reproduce it.

Can you try instrumenting the code to see if you git the timeouts and/or get any exceptions? Relevant bits are: https://github.com/igrigorik/videospeed/blob/master/inject.js#L380

**Comment by evodoc** [comment] 2017-05-16 22:44
I don't know what that means.

**Comment by baz357** [comment] 2017-05-20 11:29
I experienced the bug too recently. Right now I can't reproduce it.

Just wanted to let you know.

**Comment by canarslan12** [comment] 2017-05-23 18:49
I can reproduce it.
if mousedown and mouseup events are too close each other, it happens.

**Comment by baz357** [comment] 2017-05-23 21:18
@canarslan12: Oh yeah, that's it!

**Comment by igrigorik** [comment] 2017-05-23 22:43
> if mousedown and mouseup events are too close each other, it happens.

Not sure I follow.. How do I reproduce this?

**Comment by canarslan12** [comment] 2017-05-24 05:24
Click mouse button from touchpad if you have. Remove your finger as soon as possible.

**Comment by igrigorik** [comment] 2017-05-24 05:48
Yep, and nope, can't reproduce.. Which OS / device are you using?

**Comment by baz357** [comment] 2017-05-24 09:24
It's strange and hard to reproduce. Here, it *not always* happens "if mousedown and mouseup events are too close each other", and sometimes it happens if the mouse clicking happens slower.

Windows 10 here.

**Comment by canarslan12** [comment] 2017-05-24 10:02
w10 / chrome
only touchpad can do this

**Comment by canarslan12** [comment] 2017-05-24 10:16
checked js file and can not found a problem;
problem is css file
```
:host(:hover) #controls {
  display: inline;
}
```
here is not working

**Comment by igrigorik** [comment] 2017-06-25 20:19
Testing on a win 10 + latest Chrome.. still can't reproduce this. 

@canarslan12 what's the issue with above CSS?

**Comment by canarslan12** [comment] 2017-06-25 21:02
![image](https://user-images.githubusercontent.com/5208103/27519719-47315ef2-5a02-11e7-912e-00924bf00675.png)
for showing `.controls` on screen, both `.controller` and `.vsc-controller` need focus. Maybe merging them into only one statement might fix it.

**Comment by igrigorik** [comment] 2017-06-26 05:14
I wish I could reproduce this.. Can you try and isolate this behavior into a demo snippet on JS fiddle?    This is starting to smell like a Win platform implementation bug for Chrome, and we should fix it there if that's the case.

**Comment by evodoc** [comment] 2017-07-02 14:36
I don't use touchpad, I'm not on a laptop. By the way my OS is Win 7 if it matters.

**Comment by canarslan12** [comment] 2017-08-20 13:58
I have tested it in performance tab and here are the results, I hope that from it you understand the situation. You can ask any detailed question to me
Normal one:
![normal](https://user-images.githubusercontent.com/5208103/29495411-65483de8-85c7-11e7-972e-16640201d73e.PNG)
Buggy one:
![buggy](https://user-images.githubusercontent.com/5208103/29495412-654e3900-85c7-11e7-9219-4c23ebd626db.PNG)

**Comment by igrigorik** [comment] 2017-08-27 17:35
@canarslan12 thanks, but I don't see anything obvious that would explain the behavior. 

The logic flow is pretty straightforward:
- Each click triggers runaction: https://github.com/igrigorik/videospeed/blob/b3db296c0a44632da0762fe08fb8e268976fb2e6/options.js#L18
- runAction calls showController: https://github.com/igrigorik/videospeed/blob/b3db296c0a44632da0762fe08fb8e268976fb2e6/inject.js#L302
- showController resets the 2s timer used to hide the controller: https://github.com/igrigorik/videospeed/blob/b3db296c0a44632da0762fe08fb8e268976fb2e6/inject.js#L377-L387

**Comment by canarslan12** [comment] 2017-08-27 18:55
vcs-show class(showController) is not doing anything related to this issue. nor trying to fix, neither cause of the issue

**Comment by igrigorik** [comment] 2017-08-27 21:19
@canarslan12 apologies for being dense.. but how is the above example related to this issue? The animation is triggered by the setTimeout -- the only way for it to kick-in is to click after 2s has elapsed.

**Comment by canarslan12** [comment] 2017-08-27 21:59
your css has above code and I think problem is hidden here.
when you click top part of button, even if your mouse still on top of button, button's opacity is not 1.0
```
:host(:hover) #controls {
  display: inline;
}
```
Note: sorry about my English

**Comment by igrigorik** [comment] 2017-08-27 22:56
If you remove the CSS you're highlighting above, does the problem go away in the plugin?

**Comment by canarslan12** [comment] 2017-08-27 23:40
no, it became almost always* invisible 
* expect dragging:
```
#controller.dragging #controls {
  display: inline;
}
```

**Comment by canarslan12** [comment] 2017-08-27 23:57
by the way title is misleading. only #control part is hidden not all of them.

**Comment by igrigorik** [comment] 2017-08-28 20:36
Can you record a screencast of what's happening? I think I'm still hazy on the actual issue.. :-)

**Comment by canarslan12** [comment] 2017-09-13 22:19
after clicking `>>` button in panel, right part becomes invisible iff my `mouse up event` is too quick
![image](https://user-images.githubusercontent.com/5208103/30403458-6facd1b4-98ea-11e7-9952-59d9a8e6048c.png)

(red field is where my mouse)

**Comment by igrigorik** [comment] 2018-06-16 16:37
I believe this should have been fixed in recent version. Reopen if there is more to be done here.

**Closed by igrigorik** 2018-06-16 16:37 UTC
Labels: blocked:feedback

**Comment by evodoc** [comment] 2018-06-21 13:44
Unfortunately I see no change of behavior. By the way I'm not using a touchpad.
