### ISSUE TITLE
Does not adjust playback speed on twitch anymore

### ISSUE THREAD

**Issue by Kushurando** [igrigorik/videospeed#593] opened 2020-02-15 21:09 UTC
Hey, so since a few weeks I can't adjust the playback speed of twitch anymore when it is playing at 1.03 to catch up with the buffer, can we get a fix for this or is this out of your control? the audio distortion from it is quite annoying

**Comment by ChadBailey** [comment] 2020-02-16 21:10
Duplicate of #584 , going to close out and continue discussion there.

**Closed by ChadBailey** 2020-02-16 21:10 UTC
