### ISSUE TITLE
Speed Reset

### ISSUE THREAD

**Issue by juztrio** [igrigorik/videospeed#388] opened 2018-11-14 17:45 UTC
Hi, the speed always reset to 1x even after i checked "remember playing speed",

**Comment by V-Bernstein** [comment] 2018-11-15 23:40
I've noticed this as an issue with the new Youtube video player.

Every time you toggle fullscreen mode the speed resets. This goes both ways; going into fullscreen and out of it too.

It might have to do with their new feature where you can scroll down in the fullscreen mode to see comments.

**Comment by juztrio** [comment] 2018-11-16 12:45
Well, mine is not youtube. It's multiple videos in one page. So i think it's not the same.

**Comment by canarslan12** [comment] 2018-12-12 08:39
Can you share a public URL for us, if it's still there

**Comment by tomdaniel0x01** [comment] 2018-12-14 16:40
I am facing the same problem. This is extremely annoying!

Every time I enter or exit full screen mode on YouTube the playback speed resets. It only started happening after I recently updated.

**Comment by enviedbymost** [comment] 2018-12-17 23:53
@tomdaniel0x01 

I have the same problem as you. If you play/pause or full screen any browser video, the control resets to x1.0.

This happened as soon as I upgraded to the latest version of Chrome. :(

**Comment by igrigorik** [comment] 2019-04-18 14:08
I believe this should be addressed in latest release. If the problem is still there, please reopen.

**Closed by igrigorik** 2019-04-18 14:08 UTC
