### ISSUE TITLE
PluralSight Speed Unalterable

### ISSUE THREAD

**Issue by DavidBraun777** [igrigorik/videospeed#531] opened 2019-10-09 17:15 UTC
I have attempted to use multiple resources for speeding up my education in the field of computer science. This tool came the closest to assisting me in this endeavor. Can we look more into, maybe not just altering the Embedded Player, but rather rewriting it on the fly with add-ons for more control.

**Comment by thewheat** [comment] 2019-10-12 06:02
Hi David! I believe this issue is the same as https://github.com/igrigorik/videospeed/issues/521 and it looks like PluralSight has some custom functionality that looks to be interfering with the way this extension works 😞

I've taken a quick look at haven't found an obvious way around it but perhaps somebody with more knowledge / time / experience can help shed some light into how we can get it fixed 🤞

**Comment by ChadBailey** [comment] 2019-11-10 06:01
Unfortunately, this bug highlights a striking limitation of JavaScript. There is no way to remove an event listener if you can't supply the original function to your removal command. In the case of PluralSight that's an anonymous function which makes it literally impossible to remove.

I'm not saying this bug _can't_ be fixed, but I am saying it can't be fixed without taking some pretty ugly hacky approach. I worked at it for a good while and was unable to find any effective solution for stripping or overloading the event listener that sets the playback rate back as soon as it's altered.

**Comment by jacobcolbert** [comment] 2019-11-19 06:08
Duplicate of #521

**Closed by jacobcolbert** 2019-11-19 06:08 UTC
