### ISSUE TITLE
when unpausing video speed is set to 0.9

### ISSUE THREAD

**Issue by MichaelYou9999** [igrigorik/videospeed#461] opened 2019-04-23 13:55 UTC

**Comment by jacobcolbert** [comment] 2019-04-23 14:47
How long have you had this problem? Can you give a website it is affecting? Do you have remember speed on? What version of Video Speed Controller do you have (chrome://extensions)? What version of chrome?

**Comment by 0xC0FFEE** [comment] 2019-04-24 14:04
I'm currently suffering from the same problem. FWICT it appeared during the last week.

Youtube is definitely affected, but it seems to be broken on all other pages as well.

The problem is only present, when remember speed is turned on. When it is off, the speed is not reset when un-pausing a video.

Chrome version: 74.0.3729.108 beta (however from my tests it's also broken on the latest stable release)
Video Speed Controller version: 0.5.5

**Comment by pepijnmm** [comment] 2019-04-25 20:12
Same problem.
when I pause a video or open a new video it seems to reset the speed to 1.0(seems different for every person so maybe that's the old saved speed for youtube on my chrome).

**Comment by jacobcolbert** [comment] 2019-04-25 20:20
This should also be fixed by #458.

**Comment by zenwarr** [comment] 2019-04-26 16:02
Same here, speed is restored to the remembered value after unpausing a video (at least on YouTube) for some days. Vivaldi 2.5.1511.4, Linux

**Comment by 0xC0FFEE** [comment] 2019-04-29 16:57
I can confirm that the issue has been fixed for me in Video Speed Controller 0.5.6 :+1: 

Thanks!

**Comment by igrigorik** [comment] 2019-04-29 18:25
@jacobcolbert thank you for landing the fix! 

Closing.

**Closed by igrigorik** 2019-04-29 18:25 UTC
