### ISSUE TITLE
Video Speed Does not Work

### ISSUE THREAD

**Issue by clopar** [igrigorik/videospeed#398] opened 2018-12-09 22:18 UTC
I use this app more than anything, and all of the sudden it stopped working. See video for what's going on - https://www.useloom.com/share/3f67ab0ec8794270b2464f332dfc925b

Any suggestions?

**Comment by v1adko** [comment] 2018-12-11 07:56
Yep, same for me - huge issue.

**Comment by igrigorik** [comment] 2018-12-12 04:01
Dupe of https://github.com/igrigorik/videospeed/issues/394. Closing, let's continue there.

**Closed by igrigorik** 2018-12-12 04:01 UTC
