### ISSUE TITLE
Control Regularly Doesn't Show Up

### ISSUE THREAD

**Issue by NetJon** [igrigorik/videospeed#576] opened 2020-01-10 23:34 UTC
The speed controls often don't show up on Youtube or Vimeo.

Here is the latest:  https://player.vimeo.com/video/352485178?api=false&autoplay=auto&byline=false&color=%23444444&portrait=false&title=false

No matter what I do (including trying different browser with no cookies etc.) the controls do not show up on that video.

**Comment by eisbehr** [comment] 2020-01-13 16:57
Looks like a duplicate of #572, which was closed because it is fixed in the most recent release, but the version on the chrome web store still appears to be the broken 0.5.8 release.

**Comment by igrigorik** [comment] 2020-01-14 05:47
Triple facepalm! Pushed the tag but did not rev the version number in the manifest. 

Rolling out now: https://github.com/igrigorik/videospeed/commit/0389c61db733e86698edc1e1cd5e4298a2777c1d/checks?check_suite_id=399171106

**Closed by igrigorik** 2020-01-14 05:47 UTC

**Comment by NetJon** [comment] 2020-01-14 08:35
Just updated to 0.5.9.

Hopefully that'll work.  :-)

**Comment by NetJon** [comment] 2020-01-14 08:36
Well, it DOES work now on the specific example vimeo video that I gave earlier.

So that is a good sign.

Thanks.
