### ISSUE TITLE
Override YouTube keyboard shortcuts?

### ISSUE THREAD

**Issue by alon91** [igrigorik/videospeed#385] opened 2018-11-05 03:57 UTC
Hello! Love VSC -- it has become one of my most indispensable Chrome extensions. I've been using it for years in same way, hence my feature request.

The recently-introduced YouTube miniplayer can as of recently be triggered by the keyboard shortcut `i`. Unfortunately for me I've had `i` mapped to 'Reset Speed' in VSC for years. Unlike some other Chrome extensions (Vimium, for example), VSC does not appear to override YouTube's native keyboard shortcuts.

Have the developers of this extension considered this issue? Would love to be able to keep my setup rather than undo years of muscle memory. Thanks!

**Comment by igrigorik** [comment] 2018-11-10 15:51
> Unlike some other Chrome extensions (Vimium, for example), VSC does not appear to override YouTube's native keyboard shortcuts.

Hmm, are you familiar with how Vimium claims precedence? I've not found a way to override site defaults.. Sounds like its worth investigating.

**Comment by alon91** [comment] 2018-11-12 17:53
Hello Ilya! Thanks again for this great extension.

Alas, I'm not a SWE so don't know how things work with other extensions. Vimium's github page is [here]( https://github.com/philc/vimium), but don't know how easy it is to figure out what they are doing. [This](https://github.com/philc/vimium/wiki/Tips-and-Tricks#using-the-escape-key-in-inputs) wiki page specifically mentions the `passNextKey` command which passes certain key commands to the page, so could be a good starting point!

**Comment by igrigorik** [comment] 2018-11-19 06:43
Thanks for the pointers! Doing some more digging

- Vimium [installs a global listener](https://github.com/philc/vimium/blob/339f37fb5c19f5129c7757294d8c5968be9c9db2/content_scripts/vimium_frontend.coffee#L153-L164)
- Events are captured and Vimium calls `stopImmediatePropagation()`
  - https://github.com/philc/vimium/blob/17fb86e02971948f90215934cbe5417674364a29/lib/handler_stack.coffee
  - https://github.com/philc/vimium/blob/17fb86e02971948f90215934cbe5417674364a29/lib/dom_utils.coffee

Definitely worth experimenting with on this side as well.

**Comment by canarslan12** [comment] 2018-11-26 10:52
my pull request has this feature and it is working good. you can download [this](https://github.com/igrigorik/videospeed/pull/350) version.

**Comment by SolveAllProblemsRightNow** [comment] 2018-12-15 13:52
vimium has long had a problem of disabling youtube default shortcuts, i dont think they've ever fixed this

for the rare times it (youtube default shortcuts) actually worked on youtube, it's cos youtube changed something on there site, it seems

if there is a way to override specifically the shortcuts you the user have set in this extension, then it would be helpful/useful (as some shortcuts on youtube arent useful and should be overrided with w/e shortcuts the user sets on this extension)

disabling all youtube shortcuts is fukking garbage & trash, and breaks the youtube site entirely, and would be completely worthless

so dont waste coding time on such bad & worthless UX

**Comment by canarslan12** [comment] 2018-12-15 13:55
it is already developed and published. you can use it in options/experimental settings.
it works like expected expect it also block keys everywhere. such as gmail's new message form.

**Comment by SolveAllProblemsRightNow** [comment] 2018-12-15 13:56
your comment is a duplicate of what you already said

and i already said it's 100% worthless and not worthwhile

**Comment by canarslan12** [comment] 2018-12-15 14:03
I don't know anything about vimium. based on my tests, vsc works fine.
youtube default shortcuts is not actually worked once with force field true on my end.

> if there is a way to override specifically the shortcuts you the user have set in this extension, then it would be helpful/useful

yes, it is just disabling the keys you bind with disable keybindings. 
> disabling all youtube shortcuts is fukking garbage

yes it's garbage but **without testing my implementation**, your comment is also garbage.

**Comment by SolveAllProblemsRightNow** [comment] 2018-12-15 14:06
if you dont know any other ways, then you've not added anything of value or worth to this thread and you're cluttering up the thread

so it's garbage, and we have that cleared up, with or without testing, as it's needless, and it would be a waste of time to download garbage, which you had repeated

**Comment by canarslan12** [comment] 2018-12-15 14:17
I did not say I don't now any other ways, I just said that I do not know vimium. test vsc not vimium.

**Comment by SolveAllProblemsRightNow** [comment] 2018-12-15 14:19
and you didnt say you knew of any good ways, and without that, you can stop commenting this already

and i dont care if you know vimum or not, cos you clearly do not know UX, and that is what essentially matters here

**Comment by igrigorik** [comment] 2018-12-15 17:33
@SolveAllProblemsRightNow let's please keep the feedback constructive; no ad hominem.

To recap where we are: @canarslan12 implemented optional+experimental feature that cancels event propagation after VSC processes input. This _does not_ strictly guarantee that no other event handlers will run, because we cannot guarantee that VSC is the first handler in the queue. However, in practice it seems to work well enough.

Given that the requested feature is supported, closing this issue.

ty all!

**Closed by igrigorik** 2018-12-15 17:33 UTC
