### ISSUE TITLE
Controls don't appear any more

### ISSUE THREAD

**Issue by aboralli** [igrigorik/videospeed#105] opened 2016-05-22 10:05 UTC
Speed controls were working fine yesterday, but I cannot make them appear today. I have restarted browser several times and result is the same.

**Comment by igrigorik** [comment] 2016-05-22 16:01
@aboralli which website(s)?

**Comment by aboralli** [comment] 2016-05-23 09:59
https://u83050.ct.sendgrid.net/wf/click?upn=joepy5r7yQp3SU6BSoPus0vGKBtkMqWV5Zdh-2FYPWyVEnEg5oI209lylZTVe2ZuIV_poA-2BMqqfoFR3nuKGTq-2BXCYNKlxcIb1B2e3Xkaar1aDDyj9cnIqmxgs9D60E1JYrd-2FjNp7kE1Af6JsE2nePzfSiANMapNC5ZWQoFdl0XjOz9eNgRP26ddyU-2BgP-2FOJaF6biH12PYDnPEqmiKSj4z8NRxuRqFmYPz4ai5JL6JEkOJsiJE-2FW3yOQE4zekVrOvp1nJ3LU-2Fi3rRv164aMKHWdGGg-3D-3D

But the access is restricted. I tried other sites with the same result.
Em 22/05/2016 13:02, "Ilya Grigorik" <notifications@github.com> escreveu:

**Comment by igrigorik** [comment] 2016-05-23 14:44
Unfortunately I can't open that. I get redirected to a login screen.

**Comment by snizlefoot** [comment] 2016-05-23 22:59
the controls have disappeared on all the websites I have tried....
Netflix 
youtube
random webms

**Comment by igrigorik** [comment] 2016-05-23 23:06
That doesn't sound right. Which Chrome version are you on? Can you try closing all the windows and restarting it?

**Comment by snizlefoot** [comment] 2016-05-24 04:02
yup that was the reason, my chrome didn't auto update. Thanks for the help.

**Comment by clipped-osprey** [comment] 2016-05-26 13:10
Hi, I have the same issue from around the same time on the website stan.com.au

It was working fine before, and I have contacted their team to ask if there was a change in the way the videos were played back.

My chrome has been updated to the latest version.

Let me know if there's anything else I can do to help. :)

**Comment by mboezio** [comment] 2016-05-26 18:48
Hello, 

I have been experiencing the same problem. To get around it I have been logging into different workstations at my firm and installing the plugin. Now none of them are working. So it is still working on my personal laptop. 

Perhaps it has to do with the latest chrome update? 

Chrome Version 43.0.2357.134 m       --- on the desktops that aren't working.

**Comment by igrigorik** [comment] 2016-05-26 19:53
> Chrome Version 43.0.2357.134 m --- on the desktops that aren't working.

That is ancient -- released ~year ago! Current stable is M50. Is there any reason why you're locked on that release and can't upgrade? 

Most recent release _is_ leveraging new features which were probably not available in M43.

**Comment by mboezio** [comment] 2016-05-26 20:13
Hmm.. I'll have to look into it. My initial guess is that it might have to do with flash. Thank you for the response. i'll post again if I find anything that may be useful for others, or if I have any other questions.

**Comment by kintosh** [comment] 2016-05-26 20:19
Same here. Not working anymore. :/

**Comment by igrigorik** [comment] 2016-05-26 20:21
@kintosh which Chrome version?  Any particular page?

**Comment by kintosh** [comment] 2016-05-26 20:28
@igrigorik I checked the settings and the shortcuts had disappeared and I couldn't set it or restore it to default, so I just removed the extension, re-installed it and it just got back working again! :dancer: :+1:

tyvm for your amazing app.

**Comment by igrigorik** [comment] 2016-05-26 20:50
@kintosh cool, glad to hear!

**Comment by clipped-osprey** [comment] 2016-05-27 11:40
Hi, my chrome is Version 51.0.2704.63 m

**Comment by igrigorik** [comment] 2016-05-27 15:16
@clipped-osprey do the controls show up on other sites - e.g. youtube? Unfortunately I can't test stan.com.au because all video content there is behind a paywall / signup.

**Comment by clipped-osprey** [comment] 2016-05-27 16:16
Yes it does. :)

Yt Netflix and select videos on Facebook all work

**Comment by igrigorik** [comment] 2016-05-29 19:42
@clipped-osprey interesting. Unfortunately I can't debug it on this end. I attempted to sign up for the trial, but they require a valid Australian postcode. If they (or you) can provide a test account (you can message me in private), I can take a look.. Otherwise, *shrug*.

**Comment by dazza826** [comment] 2016-06-05 01:01
I am having the same issue as @clipped-osprey - I can provide a test account for Stan if you don't mind taking a look? Really miss being able to 2x speed everything.

**Comment by igrigorik** [comment] 2016-06-09 22:25
@dazza826 @clipped-osprey just pushed some additional updates in https://github.com/igrigorik/videospeed/commit/b0547496c9f3dfcccf844a62295ece150621104b. Can you verify that Stan videos are working? You'll have to git pull the updates and install it as an unpacked extension.

**Comment by clipped-osprey** [comment] 2016-06-10 02:59
Hi. Sorry I don't have access to my computer for a few days, so I can't
verify the build/test the new one.

I can confirm that the build that you emailed me was working well with no
issues as of yesterday.

**Comment by dazza826** [comment] 2016-06-10 03:28
Sure I can take a look and see if it works. The previous commit you advised
to test seems to work fine. I did encounter an issue with the previous
commit (when the video was left on standby for more than around 5 minutes)
it would crash the video and say an unexpected error occurred.

**Comment by igrigorik** [comment] 2016-06-19 18:49
Resolved in master, shipping in 0.3.1. Closing, feel free to reopen if the problem persists post 0.3.1.

**Closed by igrigorik** 2016-06-19 18:49 UTC
