### ISSUE TITLE
Extension repeatedly being "corrupted"

### ISSUE THREAD

**Issue by willashley23** [igrigorik/videospeed#504] opened 2019-08-13 04:06 UTC
Nearly every day, I have to go the extensions viewer to "repair" the extension. The extension has a warning on it saying "this extension may have been corrupted." What could be happening here? I would guess that if I had some kind of malware trying to manipulate my extensions it would be happening to others, but it only happens to this one. I'm on the latest version of Chrome.

**Comment by hadicodes** [comment] 2019-08-14 16:38
I do want to first say a HUGE Thank you to the creators of this extension. It is a God send! 

Recently though, I am having the exact same issue as willashley23. **Nearly every day, I have to go the extensions viewer to "repair" the extension. The extension has a warning on it saying "this extension may have been corrupted." Sometimes, the extension breaks several times a day.**

I'm also using the latest version of Chrome: Version 76.0.3809.100 (Official Build) (64-bit).

The only change I have made in the settings is to add my own keys for advancing and rewinding.

What could be the problem here and how can we resolve this specific issue of the extension corrupting multiple times?

**Comment by jacobcolbert** [comment] 2019-08-15 00:22
Closing as duplicate of #492.

Unfortunately I have no idea what is going on and can't replicate.

**Closed by jacobcolbert** 2019-08-15 00:22 UTC
