### ISSUE TITLE
Feature suggestion - option that auto-display when change speed

### ISSUE THREAD

**Issue by mbevin** [igrigorik/videospeed#172] opened 2017-01-31 23:24 UTC
So if the user has it hidden by default or has hidden by pushing V, then having an option so that, when they change speed using D/S, it could for a few seconds be visible (so the user sees that the speed has in fact changed and what the new speed is) ....

**Comment by xftroxgpx** [comment] 2017-04-11 11:27
It's currently auto-hidden by default, and when you do change the speed it shows up for a few seconds.

The only issue would be if you press 'V', you can't get it back to 'auto-hidden' state, because it's now either 'always shown' or 'always hidden'.

Commenting out this line in `inject.js` seems to do it:
`//controller.classList.add('vsc-manual');`
Now 'V' toggles between 'auto-hidden' and 'always hidden'.

**Comment by igrigorik** [comment] 2017-04-18 05:10
Copying feedback from Chrome support channel...

> When you don't move your mouse on a video for a few seconds, everything normally gets autohidden. This widget is persistently shown on the video though. My suggestion would be to show the speed controller for a few seconds when the video starts (to indicate to users where it is located), then add a CSS class that will apply opacity:0 to it. Then when a user hovers over the contol again (or when they move their mouse on the video), the opacity changes back to 1. Currently I am overriding this manually with a Chrome extension called Stylish, and the following CSS: .vsc-controller { height: 50px; opacity: 0; width: 250px; float: left; position: absolute; z-index: 101; } .vsc-controller:hover { opacity:1; }

**Comment by igrigorik** [comment] 2017-04-23 15:49
From #205:

> However, after clicking to speed up again, it will minimise again. This makes it difficult to get up to a high speed quickly, because you have to expand, speed up, (it minimises itself), expand, speed up (minimised)... etc.

**Comment by igrigorik** [comment] 2017-04-23 17:15
> The only issue would be if you press 'V', you can't get it back to 'auto-hidden' state, because it's now either 'always shown' or 'always hidden'.

Yep, that's by design. "V" is meant as a manual mode, which a number of users requested to override any default auto hide/show behaviors. I don't think we want to change that.

> When you don't move your mouse on a video for a few seconds, everything normally gets autohidden. This widget is persistently shown on the video though. My suggestion would be to show the speed controller for a few seconds when the video starts (to indicate to users where it is located), then add a CSS class that will apply opacity:0 to it. Then when a user hovers over the contol again (or when they move their mouse on the video), the opacity changes back to 1.

That's exactly the behavior we have for YouTube, because we can hook into related events there and sync the controller. Getting similar behavior for all other platforms would be rather tricky though: the hide part is easy, but knowing _when_ to show the controller becomes really hard because the hover target varies based on player. I've stayed away from trying to be "too smart" because it quickly breaks down in various edge cases.. My recommendation here is to use manual override "V" to hide/show the controller.

> However, after clicking to speed up again, it will minimise again. This makes it difficult to get up to a high speed quickly, because you have to expand, speed up, (it minimises itself), expand, speed up (minimised)... etc.

We currently have a 2s timeout between clicks -- if nothing happens, the controller will collapse. As long as you're clicking <2s, it should stay open. 

--

Closing, I don't think there is anything code-actionable here.

**Closed by igrigorik** 2017-04-23 17:15 UTC
Labels: bug
