### ISSUE TITLE
Overlay appears over Imagus popups

### ISSUE THREAD

**Issue by garyking** [igrigorik/videospeed#286] opened 2017-11-01 02:09 UTC
When using this extension with [Imagus](https://chrome.google.com/webstore/detail/imagus/immpkjjlgappgfkkfieppnmlhakdmaab?hl=en), it appears over Imagus popup images, when they aren't even videos. 

[Screenshot](https://user-images.githubusercontent.com/343940/32256867-2fcadf8c-be88-11e7-80d1-28856bc10729.png)

**Comment by igrigorik** [comment] 2017-12-10 19:46
It appears that imagus injects into the VS container, which results in the controller showing up...

![image](https://user-images.githubusercontent.com/10652/33808640-100ece5c-dd9f-11e7-8acd-5fffba6d3253.png)

That's a tricky one / weird random interaction between plugins; VS is not doing anything wrong per se.

**Comment by garyking** [comment] 2017-12-10 22:07
I don't know exactly how either addon works, but I thought that Imagus creates its own container for popups, so why would VSC code be in that container too?

**Comment by igrigorik** [comment] 2017-12-10 23:55
It's accidental behavior. Imagus injects its preview into VSC container and voila.. VSC shows up.

**Comment by canarslan12** [comment] 2018-12-15 14:50
there is no vsc in images now. can be closed

**Comment by igrigorik** [comment] 2018-12-15 17:13
Indeed, looks to be a-ok now — yay! Closing.

**Closed by igrigorik** 2018-12-15 17:13 UTC

**Comment by garyking** [comment] 2018-12-15 18:58
VSC still appears in Imagus hovered images for me.

**Comment by canarslan12** [comment] 2018-12-15 19:53
I can't reproduce this in my version(should be same with yours) of app.
![image](https://user-images.githubusercontent.com/5208103/50046893-1f455580-00bc-11e9-8855-59f38a16f1a4.png)

**Comment by garyking** [comment] 2018-12-15 19:58
Try on any of the images [on this page](https://imgur.com/t/photography).

**Comment by canarslan12** [comment] 2018-12-15 20:08
thanks for your help.
since they use video element for displaying images, it is intended in our side. 
Can you try to connect them and say images should use img tag instead of video. they might say that it is by design but...

**Comment by garyking** [comment] 2018-12-15 20:12
So you're saying that Imgur, not Imagus, uses the video element, so that's why images from Imgur that show their Imagus hover will have the VSC overlay, since VSC thinks it's a video?

I can't imagine I can convince Imgur to change this. Unless you are saying that it's up to Imagus to change this, instead?

**Comment by canarslan12** [comment] 2018-12-15 20:14
I mean imagus not imgur. Yes you get it correctly, sorry for my English since i'm not native speaker.

**Comment by garyking** [comment] 2018-12-15 20:34
Why does Imagus use video elements for image hovers from Imgur, but image elements for image hovers on Reddit? Wouldn't that be because the source file is also the respective video/image element, too, then? Since it seems that the image hover from Reddit in your screenshot doesn't have the VSC overlay, but that isn't the case on Imgur.

**Comment by canarslan12** [comment] 2018-12-15 20:39
they also use video element for images on reddit but due to some problems* on reddit we can't see vsc even though it is created. 
* it is because of we have site specific condition for reddit which causes this problem.

**Comment by garyking** [comment] 2018-12-16 04:49
If there's a specific rule that "fixes" this for Reddit, then that would explain why VSC does not appear on Imagus overlays on Reddit, but it does for Imgur. They also appear for other sites, like [here on Flickr](https://www.flickr.com/explore). 

So this issue is not resolved at all.
