### ISSUE TITLE
Speed keeps dropping to 0.00

### ISSUE THREAD

**Issue by Benu-Athanasia** [igrigorik/videospeed#258] opened 2017-09-05 02:58 UTC
I've noticed this on two laptops; I'll be watching Youtube or an FB video and the speed will go from 1.00 to 0.00. Both times, nothing was on the keyboard.

**Comment by canarslan12** [comment] 2017-09-07 11:37
I can't reproduce this.
Any other extensions you installed, that could be conflicting?

**Comment by igrigorik** [comment] 2017-09-09 05:04
Ditto, can't reproduce. Is the video rebuffering when it happens?

**Comment by igrigorik** [comment] 2017-09-16 16:13
Closing, please feel free to reopen if you can provide more details / steps on how to reproduce.

**Closed by igrigorik** 2017-09-16 16:13 UTC
