### ISSUE TITLE
Plex: Only works on first played video.

### ISSUE THREAD

**Issue by Tenerezza** [igrigorik/videospeed#368] opened 2018-08-04 14:39 UTC
It works pretty well overall with Plex web player ( https://www.plex.tv/ ), the issue is that it only works for the first video you play, the second+ video the control does not show up nor does the shortcut works, it also revert back to the initial speed

**Comment by bbobrian** [comment] 2018-09-05 20:41
I'm seeing similar behavior, which I've seen previously and then it seemed to resolve itself. But now it's back. Not sure if it's due to updates in PlexWeb or Chrome. However, I have noticed that the second+ video does play at the same speed as the previous video, even though the videospeed controls do not appear.

**Comment by sflesch** [comment] 2018-09-08 23:02
Glad to know it's not just me. Hoping it gets looked at. It's been bugging me for a while, but I finally decided to see what was going on.

**Comment by Pythor** [comment] 2018-09-09 00:56
Still experiencing this, and it kills me...  If we can't stop Plex from unloading the extension, is there any way to add a hotkey to reload the extension without having to reload the whole page?

**Comment by captainevdo** [comment] 2018-09-26 14:42
Unfortunately, I think this is due to either plexweb or chrome as bbobrian mentioned.  When this issue arose last year, the dev released a quickfix prior to wide release.  By running the developer extension I was able to circumvent the issue.  Since it rearose, I went back to that unpacked version and it persists, so it isn't do to changes made by igrigorik.  I've posted in the plexforums to see if anyone over there has solved it.  Pythor's idea of a quick extension reload is a good one though.

**Comment by sflesch** [comment] 2018-09-26 19:13
Did you find anything on Plex? I looked a bit, but didn't get far.

**Comment by captainevdo** [comment] 2018-09-26 19:47
> Did you find anything on Plex? I looked a bit, but didn't get far.

Made a new post because I didn't find anything germane to the topic.  Will keep everyone updated if there are responses.

**Comment by captainevdo** [comment] 2018-10-04 06:12
The problem has now extended to the main server player, not just plexweb.... =/

**Comment by sflesch** [comment] 2018-10-05 20:45
What's the difference between server player and plexweb?

**Comment by captainevdo** [comment] 2018-10-05 20:49
I was being a bit opaque with my terms there, sorry about that.  One being the actual user interface of my plex media server that I open locally on my network via IP etc, the other being the player I get remotely at <plex.tv/web/app>.  Up until a day or so ago, it was working on my server at home even though the remote one wasn't; now borked on both.

**Comment by Hendo-AU** [comment] 2018-10-08 15:12
Have had the same problem for a few weeks now since they updated the Plex UI

**Comment by sflesch** [comment] 2018-10-10 10:43
@captainevdo Gotcha. I usually watch on the same PC I serve from. 2mbps isn't great for serving outside.

**Comment by dirtyid** [comment] 2018-11-25 07:42
I find it's useful to have bookmarklets as backup for controlling playblack speed. Below are a couple for modifying playbackspeed of audio/video by +/- 0.5x. Good work around for times when somehow playback speed is hidden or hard to access or somehow set to 0.00. 

Increase by +0.5
javascript:(function() {var media = document.querySelectorAll('video,audio'); var rate = media[0].playbackRate+0.5; Array.prototype.forEach.call(media, function(player) {if (rate == null) {return;} else if (rate != 0) { player.playbackRate = rate; } else {player.playbackRate = 1;}}); })();

Decrease by -0.5
javascript:(function() {var media = document.querySelectorAll('video,audio'); var rate = media[0].playbackRate-0.5; Array.prototype.forEach.call(media, function(player) {if (rate == null) {return;} else if (rate != 0) { player.playbackRate = rate; } else {player.playbackRate = 1;}}); })();

**Comment by Hendo-AU** [comment] 2018-12-13 14:56
This is still a problem months later, I'm getting pretty tired of needing to reload the page every time I wanna play a new episode on Plex.

**Comment by captainevdo** [comment] 2018-12-13 15:15
Its strange given how quickly this was addressed the first time it came up last year.   The functionality of plex has lessened considerably for me since i cant just let it autoplay through but as Hendo says, have to reload everytime.  Regarding dirtyid's suggestion the issue is that the extension doesnt properly load on 2nd videos and as such those bookmarks, while a great idea, don't solve the issue.

**Comment by canarslan12** [comment] 2018-12-13 15:19
is there a public URL I can try?

**Comment by canarslan12** [comment] 2018-12-13 15:36
can you try with #402 ?

**Comment by captainevdo** [comment] 2018-12-13 15:56
No luck unfortunately.  Whether skipping to the next video manually or letting it go through autoplay, 402 displays the same behavior of the extension not loading.

**Comment by canarslan12** [comment] 2018-12-13 16:18
I tried it in the news tab and it's working correctly with next video button.
did you try it with localhost? http://127.0.0.1:32400

**Comment by captainevdo** [comment] 2018-12-14 01:02
OK, i can confirm that on the local host, the 402 fix allows the video speed picked to remain rather than reset from one video to the next, but like in my prior comment, the controller itself is inaccessible.  If you can get this to work on the app.plex.tv, its not a perfect fix but it restores the majority of functionality to the extension for my purposes.

**Comment by zestyboy** [comment] 2018-12-14 02:02
The 402 fix works for me as well. The speed and controller persist between videos on the web player (localhost). Thank you!

**Comment by captainevdo** [comment] 2018-12-14 02:47
Maybe I'm loading in the fix wrong that the controller itself isn't persisting.  Zesty, how are you getting the unpacked extension?

**Comment by captainevdo** [comment] 2018-12-14 03:56
Ok, so i def messeed up.  canarslan, your fix worked 100%.  I can also confirm it works for the webapp as well!  What a fix.  You're awesome.

**Comment by zestyboy** [comment] 2018-12-14 04:30
> The fix posted above only seems to work for me when I click the next episode button, If I completely close out of an episode and then open a new one the speed controller is gone until I reload the page.

I'm noticing this issue too. When I tested it initially I just tried it on a playlist. Still helpful though relative to the current released version.

**Comment by Hendo-AU** [comment] 2018-12-14 04:38
If someone who wants to try fix this I can give access to my Plex server for testing purposes too

**Comment by captainevdo** [comment] 2018-12-14 15:42
Have either of you tested on netflix since installing #402?  It seems that the issue we were having with plex is now there.  Could just be me but let me know.

**Comment by Hendo-AU** [comment] 2018-12-14 17:02
Netflix works perfectly fine for me with that version and the regular version

**Comment by captainevdo** [comment] 2018-12-14 17:04
I think it was a fluke.

**Comment by canarslan12** [comment] 2018-12-14 20:42
Can you try with https://github.com/canarslan12/videospeed/tree/patch-3 #403
and also in other sites such as youtube

**Comment by Hendo-AU** [comment] 2018-12-15 05:38
That one has fixed the problem

**Comment by Hendo-AU** [comment] 2018-12-15 05:51
That one has fixed the problem for Plex
Tested on Youtube and seems to be fine
Tried it on Reddit and it appears to be broken
Can't test Facebook or Twitter because I don't use them

**Comment by lennertdaniels** [comment] 2019-02-14 18:02
As far as I've been able to track down, it seems like Plex re-uses the `video` element when it starts playing a new episode. However, it also purges the DOM in some way. 
The result is that the `video` element still has a `vsc-id`, but there are no actual controls in the DOM. Because it still has a `vsc-id`, the if-statement at line 125 in `inject.js` assumes nothing has to be done.

I've tried solving it by also checking if there is an actual controller in the DOM that shares the same `vsc-id`, which works, but isn't ideal. The controls should be destroyed and re-added from scratch, to avoid multiple event listeners listening to the control buttons.

I'm new to this codebase, so I don't feel confident making this change myself. But if someone would be so kind... :)

**Comment by fent** [comment] 2019-02-14 18:58
There's already a pull request opened at https://github.com/igrigorik/videospeed/pull/403

But hasn't been updated in a while

**Comment by Hendo-AU** [comment] 2019-02-15 03:02
Yeah I hope it gets updated soon, i'm still using the modified version posted above by canarslan12

**Comment by igrigorik** [comment] 2019-02-17 19:32
> As far as I've been able to track down, it seems like Plex re-uses the `video` element when it starts playing a new episode. However, it also purges the DOM in some way.
> The result is that the `video` element still has a `vsc-id`, but there are no actual controls in the DOM. Because it still has a `vsc-id`, the if-statement at line 125 in `inject.js` assumes nothing has to be done.

Thanks for tracking this down. The fixed proposed in #403 doesn't directly address the problem (it's fixing a symptom, not the cause), which is why I haven't merged it. If any of you guys have bandwidth to dig into this, that would be much appreciated.. see [discussion here](https://github.com/igrigorik/videospeed/pull/403/files#r241940598).

**Closed** 2019-02-27 05:12 UTC

**Comment by sflesch** [comment] 2019-03-12 18:53
I've got 0.5.4 Chrome extension. Is it supposed to be fixed in this? It still doesn't work for me.

**Comment by sflesch** [comment] 2019-03-14 18:20
> > As far as I've been able to track down, it seems like Plex re-uses the `video` element when it starts playing a new episode. However, it also purges the DOM in some way.
> > The result is that the `video` element still has a `vsc-id`, but there are no actual controls in the DOM. Because it still has a `vsc-id`, the if-statement at line 125 in `inject.js` assumes nothing has to be done.
> 
> Thanks for tracking this down. The fixed proposed in #403 doesn't directly address the problem (it's fixing a symptom, not the cause), which is why I haven't merged it. If any of you guys have bandwidth to dig into this, that would be much appreciated.. see [discussion here](https://github.com/igrigorik/videospeed/pull/403/files#r241940598).

I'm still having issues with this. I have 0.5.4. Shoul dI open a issue or is there something I'm missing?

**Comment by fent** [comment] 2019-03-14 18:46
Looks like a new version hasn't been released since the last commit.

@igrigorik, if you haven't already, look into https://github.com/DrewML/chrome-webstore-upload-cli
after setting it up, uploading a new version is just a command away

**Comment by sflesch** [comment] 2019-03-18 19:32
> Looks like a new version hasn't been released since the last commit.
> 
> @igrigorik, if you haven't already, look into https://github.com/DrewML/chrome-webstore-upload-cli
> after setting it up, uploading a new version is just a command away

So the fix isn't in the Chrome webstore?
