### ISSUE TITLE
App stopped working 

### ISSUE THREAD

**Issue by GEORGEJUNGCOCAINE** [igrigorik/videospeed#394] opened 2018-12-05 12:52 UTC
All of a sudden it's stopped working for the first time

**Comment by evodoc** [comment] 2018-12-05 13:14
Same, the hotkeys still work though, only the mouse clicks are not registered. Probably the recent Chrome update messed up something.

**Comment by poush** [comment] 2018-12-05 18:21
Same here.

**Comment by princesden** [comment] 2018-12-07 06:18
It stopped working after chrome update from v70 to 71.

**Comment by paulocesar-ufu** [comment] 2018-12-07 10:50
Same here! Chrome 71

**Comment by canarslan12** [comment] 2018-12-07 10:58
Is this just mouse events or all at once? If just mouse events duplicate of
#389

**Comment by paulocesar-ufu** [comment] 2018-12-07 11:01
Only mouse events, its really duplicated of #389

**Comment by bethrobson** [comment] 2018-12-07 16:53
Yep me too, Chrome 71. Still working on Firefox.

**Comment by bethrobson** [comment] 2018-12-10 16:08
How do we find out when an update will be forthcoming?

**Comment by igrigorik** [comment] 2018-12-12 06:16
Fix should be rolling out with 0.5.3. 

Kudos to @canarslan12 for fixing this one!

**Closed by igrigorik** 2018-12-12 06:16 UTC
