### ISSUE TITLE
Annoyance: YouTube Speed Resets on Theater Mode Toggle

### ISSUE THREAD

**Issue by Chiramisu** [igrigorik/videospeed#365] opened 2018-07-31 18:35 UTC
Video Speed Version: 0.5.2

Steps to repeat:
1. Open YouTube video
1. Change speed (up or down)
1. Toggle Theater mode / Default view

This is not a breaking issue, just an annoyance.

**UPDATE**: This issue is resolved by going to the extension Settings, enabling "Remember Playback Speed," clicking Save, and refreshing the YouTube page. However, I would still argue that even without this enabled the speed should at least be preserved when switching display states for a given video.

**Comment by drewta** [comment] 2018-09-02 19:15
Have the same issue with speed resetting to 1.0 when toggling between normal and theater mode on any video (e.g. https://www.youtube.com/watch?v=0pO7DWIfR6Y) using either hotkey (T) or manually clicking the button. Doesn't happen when toggling between normal and full screen (e.g. issue#370). I also don't have the scroll for details function, so unsure if that's related. Using Chrome 68.0.3440.106 on a Windows 10 device.

**Comment by chadbramwell** [comment] 2019-01-01 04:52
To work around this, I added youtube.com to the blacklisted sites in settings. But I'd love a fix.

**Comment by igrigorik** [comment] 2019-04-18 14:11
Dupe of #370, let's continue there.

**Closed by igrigorik** 2019-04-18 14:11 UTC
Labels: bug
