### ISSUE TITLE
Speed resets to 1.00 after rewinding/fast forward or pause/play

### ISSUE THREAD

**Issue by kdP21** [igrigorik/videospeed#459] opened 2019-04-23 00:59 UTC
Let me apologize in advance by stating I know nothing about code and am completely new to this website. I've been having an issue with this extension over the past week and when I clicked on the extension to "Send feedback" it referred me here. So please don't crucify me if I'm completely ignorant to how posting works here and how the website is generally run!

Anyway, I have been using this extension over the past several months for my medical school lectures and it's FANTASTIC. Now I don't know how to get through school without it! I use this extension almost exclusively with Echo360 Recordings, but I tested the issue on other videos and it appears the problem is occurring everywhere, e.g. YouTube, etc.

Basically, I open a video and set it to my preferred speed - let's say at 1.50x. When I go to either rewind, fast forward, or pause and then play again, the speed reverts back to 1.00x. It does not make a difference whether I use the hot keys or click the speed/fast forward/rewind options manually. I'm constantly rewinding and fast forwarding during my lectures so it's been a pain to keep having to change the speed back to 1.50x.

I have tried adjusting the shortcut settings and checking/unchecking the "Remember Playback Speed" but nothing fixes the problem. I never had this issue until about a few days ago. I haven't changed any settings or done any major updates as far as I can recall. Although, it is possible this may have started with the latest update of the extension. 

I saw other people here seem to be having similar issues, but that it was able to be resolved using hotkeys or checking "Remember Playback Speed". However, this is not working for me. I also saw there has been a pull request regarding a similar issue, but as I said, I have no idea how code/this website works so I don't know if the request pertains to my issue or even how pull requests work! Does the code get incorporated into the extension or do I need to copy and paste it somewhere? Again, my apologies for being technologically inept!

Any help is much appreciated. Thank you!

**Comment by jacobcolbert** [comment] 2019-04-23 02:08
This sounds equivalent to #455 so this should probably be closed and continued there in terms of a bug fix.

As to your specific questions though: 
Are you sure you are unchecking "Remember playback speed" *and* hitting the Save button when fixing the settings. There were a couple problems reported with the recent update, but to fix your issue temporarily I believe you want "Remember playback speed" *turned off.* Please let me know if you are sure that it is turned off and you are still having this problem, since I cannot recreate that situation.

If others find my pull request fixes their issue it will eventually be merged into the project and then sent out as an update. If you want to try my fix yourself you can do the following: (though note that on principle you should not install developer mode extensions unless you have reason to trust them.) 
1. Download my version at https://github.com/jacobcolbert/videospeed/archive/fix/455.zip 
2. Unzip to some folder
3. Go to chrome://extensions and turn on developer mode in the upper right corner.
4. Click load unpacked extension and navigate to the folder containing the extension.

You should then deactivate the retail version. If you do this remember to check back here to see if the problem has been fixed and pushed out, because the developer version you install will not get any updates.

Please post back if you do either of these and they fix your issue!

**Comment by kdP21** [comment] 2019-04-23 02:49
@jacobcolbert Thank you so much for getting back to me!

I just made sure to click Save after unchecking "Remember playback speed" and also downloaded your version of the extension, but unfortunately neither option fixed the issue :(

I'm going to keep messing around with it, but I very much appreciate all of your help and easy-to-follow steps, so thank you for that! I will be sure to report back if I get it working!

**Comment by jacobcolbert** [comment] 2019-04-23 03:31
Weird. I really can't replicate that problem. Just to make sure are you refreshing/opening a new tab to check if it is working right? 

You can revert to the previous version and see if that works by following the above instructions on this version. https://github.com/jacobcolbert/videospeed/archive/old.zip

**Comment by kdP21** [comment] 2019-04-23 04:07
@jacobcolbert Yep, I've been restarting Chrome each time I make a change and even restarted my laptop a few times to see if that would help.

I also just downloaded the old version (thank you for the link, by the way), but I seem to be having the same problem.

So strange, I can't imagine why this happened all of a sudden!

Here's a video of the issue if that helps at all: https://www.youtube.com/watch?v=tWLOj4PEmGE&feature=youtu.be

**Comment by jacobcolbert** [comment] 2019-04-23 06:23
huh, that is really weird. Thanks for the video. If you want to keep trying to debug this, here is (yet) another version that has some more logging added to try to figure out what is going on. https://github.com/jacobcolbert/videospeed/archive/debug.zip. Just load that extension and make another video, but with the console open (ctrl+shift+J) and filter for 'inject.js'

**Comment by kdP21** [comment] 2019-04-23 07:21
I appreciate you working with me on this! I just loaded the new extension, here's the video:
https://www.youtube.com/watch?v=EThvBQLfMHY&feature=youtu.be
I tried switching between keystrokes and clicking it manually, but it seems to have the same effect. Anyway, hope all that coding makes more sense to you than it does to me lol!

**Comment by jacobcolbert** [comment] 2019-04-23 15:33
Ah okay. I think this might be two seperate problems. You are encountering #455 *and* Echo360 is resetting your speed. Can you go back to the first version I gave you (https://github.com/jacobcolbert/videospeed/archive/fix/455.zip) and try it in youtube and see if the problem is fixed.

Sorry that echo360 is doing this and being annoying. I know how life changing VSC is. I actually tried to make you a custom version that fixed the problem, but echo360 is very aggressive about maintaining its control of the speed. I know it is nowhere as good as VSC, but in case you don't know you can change the speed in their settings by clicking on the gear.  The problem is whenever you fast forward they are changing the video speed to the speed set in their options menu.

@igrigorik this is Blocked: External

**Comment by mkgitnro** [comment] 2019-04-23 16:46
@kdP21 

Made this account just to let you know what I did that's worked. I was having the exact same issue with echo360 and none of the older versions / fixed worked for me either!

I know nothing about javascript nor really what's going on in the instance.js but after loads of console log debugging, I realised it must be echo itself doing the ratechange back to 1.0. So what I've done that seems to work so far (with zero javascript knowledge/experience) is explicitly update the settings.speeds immediately when the ratechange is performed through VSC (by me), and then setting the video playbackrate back to the stored value at the start of the ratechange eventlistener. 

I imagine this is definitely a horrible way to do it, but it works for me so far. Here's my edited version: https://github.com/mkgitnro/videospeed/blob/patch-1/inject.js if you want to try that until it's officially fixed.

@igrigorik Really sorry if I did something stupid Github-wise with how i just uploaded this for the other user. Never use Git properly.

**Comment by jacobcolbert** [comment] 2019-04-23 17:16
Very nice! I was trying to find a roundabout way of making echo360 happy, but approaching this directly is much better. I will take a look at it and see how it behaves on other sites, and whether I'd vote for its permanent inclusion.

Thanks so much for contributing! I also know nothing about javascript or github! But my love for this extension made me want to fix its problem and expand its capabilities.

**Comment by jacobcolbert** [comment] 2019-04-23 17:26
Ok. Definitely cannot be included in retail release. It disables any internal speed controls and crashes the browser on aggressive sites (like the CW streaming client) in a war over what speed it will be.

**Comment by kdP21** [comment] 2019-04-23 22:07
@jacobcolbert and @mkgitnro I just want to say that the two of you are **AMAZING**!

@jacobcolbert I reloaded the #455 fix and it worked for every other platform I was previously experiencing a problem with, including YouTube so **THANK YOU**. Also thank you so much for working so hard to find me a fix for Echo360 (it's quite the finicky program, I see).. I'm still baffled as to why this started happening out of nowhere! Echo360's speed control is nowhere near as user-friendly as VSC and I can only change the speed in units of 0.5s so VSC has been a total lifesaver for me in customizing the speed! Again, thank you so much for working so hard on my favorite extension :)

And @mkgitnro your version completely **fixed** my issue with Echo360! I'm not sure what magic you created in your version, but I cannot thank you enough!

Now someone get the two of you a freaking medal! Really, though thank you both SO MUCH.

**Comment by jacobcolbert** [comment] 2019-04-25 20:39
@igrigorik This can be closed I think. This is a problem with a specific player not allowing a ratechange.

**Comment by igrigorik** [comment] 2019-04-25 22:25
👍

**Closed by igrigorik** 2019-04-25 22:25 UTC
