### ISSUE TITLE
Multiple keys shortcut + Override shortcuts

### ISSUE THREAD

**Issue by sharkistani3awtani** [igrigorik/videospeed#387] opened 2018-11-12 12:17 UTC
Hello,
Thanks for the usefull extension that realy changerd may life, actually I have 2 requests : 

1. I would like that you give us possibility to set multiple keys for the same shortcut.
2. There is many keys already used by many sites/players as their own shortcuts, it will be great if you think to override it with VSC ones.

**Comment by canarslan12** [comment] 2018-11-26 12:16
duplicate of #347 and it's in development with #350

**Comment by igrigorik** [comment] 2018-12-12 04:43
Resolved via https://github.com/igrigorik/videospeed/pull/399

**Closed by igrigorik** 2018-12-12 04:43 UTC
