### ISSUE TITLE
Controller lifetime should be tied to src on video (no src, no controller)

### ISSUE THREAD

**Issue by SeanSilke** [igrigorik/videospeed#236] opened 2017-07-05 10:57 UTC
There is doubling of controls on vk.com video player.
I am using  0.4.8 version of plugin.
Here is screenshot.
<img width="539" alt="sy8ooncvsbcairmikjhkgw" src="https://user-images.githubusercontent.com/1077074/27861419-81963f98-6189-11e7-9e5c-26670beb9391.png">
You can reproduce this behavior by playing some videos on vk.com pages, for example https://vk.com/iskin

**Comment by igrigorik** [comment] 2017-07-05 10:58
Can you please try the latest plugin from master? We just landed a fix
yesterday that should address this.

**Comment by SeanSilke** [comment] 2017-07-05 11:23
Tried with the latest plugin from master. There is still doubling.

**Comment by igrigorik** [comment] 2017-07-05 15:54
Well, doh.. :-)

Do you have an example URL, ideally something that doesn't require a login?

**Comment by SeanSilke** [comment] 2017-07-05 16:06
Here is URL https://vk.com/iskin?w=wall475146_35849%2Fall
the login is not required.

**Comment by igrigorik** [comment] 2017-07-05 16:47
Ah, "fun" one.. The issue is because there are actually two video elements in the container, one on top of the other, and one of them doesn't have a src / servers as a placeholder for in-video ads. As a result, you see two controllers...

![image](https://user-images.githubusercontent.com/10652/27875025-09b487a4-61b2-11e7-9daf-98101daa70cf.png)

This is something I've run into before, but haven't tackled explicitly.. Arguably, we shouldn't initialize the controller for video elements that don't have a src. That said, getting this right will require some careful implementation (and additional MutationObservers on per video element, probably).

**Comment by canarslan12** [comment] 2017-08-28 11:10
Afaik, video elements can be loaded/played without src with help of js. There might be video.status etc. I hope it will help

**Comment by canarslan12** [comment] 2018-12-15 19:55
I think second one is not for adds, it is for seek bar's hover images

**Closed** 2019-05-04 16:26 UTC
Labels: enhancement
