### ISSUE TITLE
playback bar jumping / flickering into video

### ISSUE THREAD

**Issue by ghbob** [igrigorik/videospeed#295] opened 2017-11-27 08:33 UTC
I sometimes have the issue that the playback bar jumps / blinks / flickers into the video at a very annoying rate (sub-second).

It's not something I can reproduce on purpose, it's not even consistent if I reload the page.

Anyone else got this problem?

Currently on Chrome 64.0.3278.0 (Official Build) canary (64-bit)

PS: Thanks for this extension, I use it daily and find it highly useful :)

**Comment by igrigorik** [comment] 2017-12-10 19:30
I've run into this before as well. However, I saw it even when extension is disabled.. I don't believe it's caused by the extension; closing. That said, if you have evidence otherwise, please reopen!

**Closed by igrigorik** 2017-12-10 19:30 UTC
