### ISSUE TITLE
Skipping in netflix causes crash

### ISSUE THREAD

**Issue by atlas6523** [igrigorik/videospeed#84] opened 2016-02-10 21:12 UTC
Using the skip option, whether in the gui or with the shortcut keys causes the Netflix to go to the "Encountered an Unexpected Error" page.  The code is M7375.  I use the natural/already-provided skipping providing by the arrow keys, so this isn't a problem for me.  I know you said you don't have access to a Netflix account, I just wanted to let you know.

**Comment by igrigorik** [comment] 2016-02-10 23:22
Ugh. Looks like this might be related to Widevine / DRM: https://help.netflix.com/en/node/14759 - guessing, they may be explicitly disallowing seek's or some such.

**Comment by igrigorik** [comment] 2016-03-27 18:24
Closing, as I'm unable to reproduce. If only Netflix could sponsor us with a tester account.. :)

**Closed by igrigorik** 2016-03-27 18:24 UTC

**Comment by rdp** [comment] 2016-09-26 13:22
No work around known yet, unless you want to manually click on some netflix UI ref: http://stackoverflow.com/questions/27927950/controlling-netflix-html5-playback-with-tampermonkey-javascript FWIW :|
